package main

import (
	"fmt"
	"go/format"
	"strings"
)

// genGo renders package api's generated half: types, enums, params, service
// interfaces, router registration, typed client methods, events and errors.
// The hand-written half (Router, Client, Error, decodeParams) lives beside it.
func genGo(s *Schema) ([]byte, error) {
	var w writer
	w.line("// Code generated by rpcgen from schema/rpc. DO NOT EDIT.")
	w.line("")
	w.line("package api")
	w.line("")
	w.line("import (")
	w.line(`"context"`)
	w.line(`"encoding/json/jsontext"`)
	w.line(`"encoding/json/v2"`)
	w.line(`"errors"`)
	w.line(`"fmt"`)
	w.line(`"time"`)
	w.line(")")
	w.line("")
	w.line("// Keep imports used when a schema has no time or json fields.")
	w.line("var (")
	w.line("_ time.Time")
	w.line("_ jsontext.Value")
	w.line(")")
	w.line("")
	w.line("// Protocol is the protocol major version this package speaks.")
	w.line("const Protocol = %d", s.Protocol)
	w.line("")

	w.line("// Error codes. JSON-RPC 2.0 defines the negative codes.")
	w.line("const (")
	for _, e := range s.allErrors() {
		w.doc(e.Doc)
		w.line("Code%s ErrorCode = %d", goName(e.Name), e.Code)
	}
	w.line(")")
	w.line("")
	w.line("// Sentinels for errors.Is: an *Error matches the sentinel with its code.")
	w.line("var (")
	for _, e := range s.allErrors() {
		w.line("Err%s = &Error{Code: Code%s}", goName(e.Name), goName(e.Name))
	}
	w.line(")")
	w.line("")
	w.line("// String is the code's schema name.")
	w.line("func (c ErrorCode) String() string {")
	w.line("switch c {")
	for _, e := range s.allErrors() {
		w.line("case Code%s:", goName(e.Name))
		w.line("return %q", e.Name)
	}
	w.line("}")
	w.raw(`return fmt.Sprintf("ErrorCode(%d)", int(c))`)
	w.line("}")
	w.line("")
	for _, e := range s.allErrors() {
		n := goName(e.Name)
		w.line("// %s returns an error with Code%s.", n, n)
		w.line("func %s(format string, args ...any) *Error { return Errorf(Code%s, format, args...) }", n, n)
		w.line("")
	}

	for _, f := range s.Domains {
		dn := goName(f.Domain)
		w.line("// ---- %s ----", f.Domain)
		w.line("")
		for _, e := range f.Enums {
			w.doc(e.Name + ": " + e.Doc)
			w.line("type %s string", e.Name)
			w.line("")
			w.line("const (")
			for _, v := range e.Values {
				w.doc(v.Doc)
				w.line("%s%s %s = %q", e.Name, goName(v.Name), e.Name, v.Name)
			}
			w.line(")")
			w.line("")
			w.line("// Valid reports whether v is one of the declared values.")
			w.line("func (v %s) Valid() bool {", e.Name)
			w.line("switch v {")
			var cases []string
			for _, v := range e.Values {
				cases = append(cases, e.Name+goName(v.Name))
			}
			w.line("case %s:", strings.Join(cases, ", "))
			w.line("return true")
			w.line("}")
			w.line("return false")
			w.line("}")
			w.line("")
		}
		for _, t := range f.Types {
			w.doc(t.Name + ": " + t.Doc)
			w.structDecl(s, t.Name, t.Fields)
		}
		for _, m := range f.Methods {
			w.doc(fmt.Sprintf("%s holds the params of %s.", paramsName(f.Domain, m.Name), wireMethod(f.Domain, m.Name)))
			w.structDecl(s, paramsName(f.Domain, m.Name), m.Params)
		}

		w.doc(dn + "Service: " + f.Doc)
		w.line("type %sService interface {", dn)
		for _, m := range f.Methods {
			w.doc(goName(m.Name) + " implements " + wireMethod(f.Domain, m.Name) + ". " + m.Doc)
			w.line("%s(ctx context.Context, p *%s) %s", goName(m.Name), paramsName(f.Domain, m.Name), resultSig(s, m))
		}
		w.line("}")
		w.line("")

		w.line("func register%s(r *Router, s %sService) {", dn, dn)
		for _, m := range f.Methods {
			w.line("r.handle(%q, func(ctx context.Context, raw jsontext.Value) (any, error) {", wireMethod(f.Domain, m.Name))
			w.line("var p %s", paramsName(f.Domain, m.Name))
			w.line("if err := decodeParams(raw, &p, %s); err != nil {", requiredList(m.Params))
			w.line("return nil, err")
			w.line("}")
			if m.result == nil {
				w.line("return nil, s.%s(ctx, &p)", goName(m.Name))
			} else {
				w.line("return s.%s(ctx, &p)", goName(m.Name))
			}
			w.line("})")
		}
		w.line("}")
		w.line("")

		w.line("// %sClient calls the %s methods; it implements %sService.", dn, f.Domain, dn)
		w.line("type %sClient struct{ c *Client }", dn)
		w.line("")
		w.line("// %s returns the %s methods.", dn, f.Domain)
		w.line("func (c *Client) %s() %sClient { return %sClient{c} }", dn, dn, dn)
		w.line("")
		w.line("var _ %sService = %sClient{}", dn, dn)
		w.line("")
		for _, m := range f.Methods {
			w.line("// %s calls %s.", goName(m.Name), wireMethod(f.Domain, m.Name))
			w.line("func (x %sClient) %s(ctx context.Context, p *%s) %s {", dn, goName(m.Name), paramsName(f.Domain, m.Name), resultSig(s, m))
			if m.result == nil {
				w.line("return x.c.Call(ctx, %q, p, nil)", wireMethod(f.Domain, m.Name))
			} else {
				w.line("var r %s", goType(s, m.result, true))
				w.line("err := x.c.Call(ctx, %q, p, &r)", wireMethod(f.Domain, m.Name))
				if strings.HasPrefix(resultSig(s, m), "(*") {
					w.line("if err != nil {")
					w.line("return nil, err")
					w.line("}")
					w.line("return &r, nil")
				} else {
					w.line("return r, err")
				}
			}
			w.line("}")
			w.line("")
		}

		for _, ev := range f.Events {
			n := eventName(f.Domain, ev.Name)
			w.doc(n + ": " + ev.Doc)
			w.structDecl(s, n, ev.Fields)
			w.line("// EventName is the wire name of %s.", n)
			w.line("func (%s) EventName() string { return %q }", n, wireMethod(f.Domain, ev.Name))
			w.line("")
			w.line("// Durable reports whether %s is kept in the changes log.", n)
			w.line("func (%s) Durable() bool { return %t }", n, ev.Durable)
			w.line("")
		}
	}

	w.line("// Services is one implementation per domain, for NewRouter.")
	w.line("type Services struct {")
	for _, f := range s.Domains {
		w.line("%s %sService", goName(f.Domain), goName(f.Domain))
	}
	w.line("}")
	w.line("")
	w.line("func (s Services) register(r *Router) error {")
	for _, f := range s.Domains {
		w.line("if s.%s == nil {", goName(f.Domain))
		w.line("return errors.New(%q)", "api: Services."+goName(f.Domain)+" is nil")
		w.line("}")
		w.line("register%s(r, s.%s)", goName(f.Domain), goName(f.Domain))
	}
	w.line("return nil")
	w.line("}")
	w.line("")

	w.line("// Methods is every method's wire name, in schema order.")
	w.line("var Methods = []string{")
	for _, f := range s.Domains {
		for _, m := range f.Methods {
			w.line("%q,", wireMethod(f.Domain, m.Name))
		}
	}
	w.line("}")
	w.line("")

	w.line("// DecodeEvent decodes the data of the named event.")
	w.line("func DecodeEvent(name string, data jsontext.Value) (Event, error) {")
	w.line("switch name {")
	for _, f := range s.Domains {
		for _, ev := range f.Events {
			n := eventName(f.Domain, ev.Name)
			w.line("case %q:", wireMethod(f.Domain, ev.Name))
			w.line("var e %s", n)
			w.line("if err := json.Unmarshal(data, &e); err != nil {")
			w.raw(`return nil, fmt.Errorf("decode event %s: %w", name, err)`)
			w.line("}")
			w.line("return e, nil")
		}
	}
	w.line("}")
	w.raw(`return nil, fmt.Errorf("unknown event %q", name)`)
	w.line("}")

	out, err := format.Source([]byte(w.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated go: %w\n%s", err, w.String())
	}
	return out, nil
}

func (w *writer) structDecl(s *Schema, name string, fields []Field) {
	if len(fields) == 0 {
		w.line("type %s struct{}", name)
		w.line("")
		return
	}
	w.line("type %s struct {", name)
	for _, f := range fields {
		w.doc(f.Doc)
		tag := f.Name
		if f.Optional {
			tag += ",omitzero"
		}
		w.line("%s %s `json:\"%s\"`", goName(f.Name), goType(s, f.ref, !f.Optional), tag)
	}
	w.line("}")
	w.line("")
}

// goType spells a type in Go. Optional scalars, enums and structs become
// pointers so absence is distinct from the zero value; lists, maps and json
// are already nilable.
func goType(s *Schema, t *TypeRef, required bool) string {
	var base string
	switch {
	case t.List != nil:
		return "[]" + goType(s, t.List, true)
	case t.Map != nil:
		return "map[string]" + goType(s, t.Map, true)
	case t.Named != "":
		base = t.Named
	default:
		switch t.Prim {
		case "bool":
			base = "bool"
		case "int":
			base = "int64"
		case "float":
			base = "float64"
		case "string":
			base = "string"
		case "time":
			base = "time.Time"
		case "json":
			return "jsontext.Value"
		}
	}
	if required {
		return base
	}
	return "*" + base
}

// resultSig is a method's Go return list. Struct results are pointers.
func resultSig(s *Schema, m Method) string {
	if m.result == nil {
		return "error"
	}
	t := goType(s, m.result, true)
	if m.result.Named != "" && !s.isEnum(m.result.Named) {
		t = "*" + t
	}
	return "(" + t + ", error)"
}

func requiredList(fields []Field) string {
	var names []string
	for _, f := range fields {
		if !f.Optional {
			names = append(names, fmt.Sprintf("%q", f.Name))
		}
	}
	if len(names) == 0 {
		return "nil"
	}
	return "[]string{" + strings.Join(names, ", ") + "}"
}

// writer accumulates generated text.
type writer struct{ strings.Builder }

// line writes one formatted line.
func (w *writer) line(format string, args ...any) {
	fmt.Fprintf(w, format, args...)
	w.WriteByte('\n')
}

// raw writes one line verbatim, for generated code that contains verbs.
func (w *writer) raw(s string) {
	w.WriteString(s)
	w.WriteByte('\n')
}

// doc writes a Go comment, wrapped at 78 columns; empty docs write nothing.
func (w *writer) doc(text string) { w.comment("// ", text) }

func (w *writer) comment(prefix, text string) {
	text = strings.Join(strings.Fields(text), " ")
	if text == "" || strings.HasSuffix(text, ":") {
		return
	}
	for _, l := range wrap(text, 78-len(prefix)) {
		w.line("%s%s", prefix, l)
	}
}

func wrap(text string, width int) []string {
	var lines []string
	var cur string
	for _, word := range strings.Fields(text) {
		if cur != "" && len(cur)+1+len(word) > width {
			lines = append(lines, cur)
			cur = word
			continue
		}
		if cur != "" {
			cur += " "
		}
		cur += word
	}
	if cur != "" {
		lines = append(lines, cur)
	}
	return lines
}
