package main

import "strings"

// genMarkdown renders docs/specs/rpc-api.md, the reference for every method,
// type and event. The wire rules live in docs/specs/rpc-protocol.md.
func genMarkdown(s *Schema) []byte {
	var w writer
	w.line("<!-- Code generated by rpcgen from schema/rpc. DO NOT EDIT. -->")
	w.line("")
	w.line("# Spec: maild RPC API (protocol %d)", s.Protocol)
	w.line("")
	w.line("Generated from [schema/rpc](../../schema/rpc). Framing, connection setup and event delivery are in [rpc-protocol.md](rpc-protocol.md). `int` is a JSON number (int64 in Go), `time` an RFC 3339 string. Optional fields may be omitted; every other field is required.")
	w.line("")
	w.line("## Errors")
	w.line("")
	w.line("| Name | Code | Meaning |")
	w.line("| --- | --- | --- |")
	for _, e := range s.allErrors() {
		w.line("| `%s` | %d | %s |", e.Name, e.Code, cell(e.Doc))
	}
	w.line("")
	for _, f := range s.Domains {
		w.line("## %s", f.Domain)
		w.line("")
		if f.Doc != "" {
			w.line("%s", oneLine(f.Doc))
			w.line("")
		}
		for _, m := range f.Methods {
			w.line("### `%s`", wireMethod(f.Domain, m.Name))
			w.line("")
			if m.Doc != "" {
				w.line("%s", oneLine(m.Doc))
				w.line("")
			}
			if len(m.Params) > 0 {
				w.fieldTable(m.Params)
			} else {
				w.line("No params.")
				w.line("")
			}
			res := "none (`null`)"
			if m.result != nil {
				res = "`" + m.result.String() + "`"
			}
			w.line("Result: %s.", res)
			if len(m.Errors) > 0 {
				w.line("Errors: `%s`.", strings.Join(m.Errors, "`, `"))
			}
			w.line("")
		}
		for _, ev := range f.Events {
			kind := "transient"
			if ev.Durable {
				kind = "durable"
			}
			w.line("### Event `%s` (%s)", wireMethod(f.Domain, ev.Name), kind)
			w.line("")
			if ev.Doc != "" {
				w.line("%s", oneLine(ev.Doc))
				w.line("")
			}
			w.fieldTable(ev.Fields)
		}
		for _, t := range f.Types {
			w.line("### Type `%s`", t.Name)
			w.line("")
			if t.Doc != "" {
				w.line("%s", oneLine(t.Doc))
				w.line("")
			}
			w.fieldTable(t.Fields)
		}
		for _, e := range f.Enums {
			w.line("### Enum `%s`", e.Name)
			w.line("")
			if e.Doc != "" {
				w.line("%s", oneLine(e.Doc))
				w.line("")
			}
			w.line("| Value | Meaning |")
			w.line("| --- | --- |")
			for _, v := range e.Values {
				w.line("| `%s` | %s |", v.Name, cell(v.Doc))
			}
			w.line("")
		}
	}
	return []byte(strings.TrimRight(w.String(), "\n") + "\n")
}

func (w *writer) fieldTable(fields []Field) {
	if len(fields) == 0 {
		w.line("No fields.")
		w.line("")
		return
	}
	w.line("| Field | Type | Meaning |")
	w.line("| --- | --- | --- |")
	for _, f := range fields {
		t := "`" + f.Type + "`"
		if f.Optional {
			t += " (optional)"
		}
		w.line("| `%s` | %s | %s |", f.Name, t, cell(f.Doc))
	}
	w.line("")
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

func cell(s string) string { return strings.ReplaceAll(oneLine(s), "|", `\|`) }
