package main

import (
	"fmt"
	"strings"
)

// genTS renders app/src/rpc/gen/api.ts: types, enums, params, events, error
// codes and the typed Client over a Transport (app/src/rpc/transport.ts).
func genTS(s *Schema) []byte {
	var w writer
	w.line("// Code generated by rpcgen from schema/rpc. DO NOT EDIT.")
	w.line("")
	w.line(`import type { Transport } from "../transport";`)
	w.line("")
	w.line("/** The protocol major version this client speaks. */")
	w.line("export const PROTOCOL = %d;", s.Protocol)
	w.line("")
	w.line("/** Error codes. JSON-RPC 2.0 defines the negative codes. */")
	w.line("export const ErrorCode = {")
	for _, e := range s.allErrors() {
		w.tsdoc("  ", e.Doc)
		w.line("  %s: %d,", e.Name, e.Code)
	}
	w.line("} as const;")
	w.line("export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];")
	w.line("")

	for _, f := range s.Domains {
		w.line("// ---- %s ----", f.Domain)
		w.line("")
		for _, e := range f.Enums {
			var vals []string
			for _, v := range e.Values {
				vals = append(vals, fmt.Sprintf("%q", v.Name))
			}
			w.tsdoc("", e.Doc)
			w.line("export type %s = %s;", e.Name, strings.Join(vals, " | "))
			w.line("export const %sValues: readonly %s[] = [%s];", e.Name, e.Name, strings.Join(vals, ", "))
			w.line("")
		}
		for _, t := range f.Types {
			w.tsdoc("", t.Doc)
			w.tsInterface(t.Name, t.Fields)
		}
		for _, m := range f.Methods {
			w.tsdoc("", "Params of "+wireMethod(f.Domain, m.Name)+".")
			w.tsInterface(paramsName(f.Domain, m.Name), m.Params)
		}
		for _, ev := range f.Events {
			w.tsdoc("", ev.Doc)
			w.tsInterface(eventName(f.Domain, ev.Name), ev.Fields)
		}

		cn := goName(f.Domain) + "Client"
		w.tsdoc("", f.Doc)
		w.line("export interface %s {", cn)
		for _, m := range f.Methods {
			w.tsdoc("  ", m.Doc)
			w.line("  %s(params%s: %s): Promise<%s>;", m.Name, optMark(m.Params), paramsName(f.Domain, m.Name), tsResult(m))
		}
		w.line("}")
		w.line("")
		w.line("function %sClient(t: Transport): %s {", f.Domain, cn)
		w.line("  return {")
		for _, m := range f.Methods {
			def := ""
			if optMark(m.Params) == "?" {
				def = " = {}"
			}
			call := fmt.Sprintf("t.call<%s>(%q, params)", tsWireResult(m), wireMethod(f.Domain, m.Name))
			if m.result == nil {
				call += ".then(() => undefined)"
			}
			w.line("    %s: (params%s) => %s,", m.Name, def, call)
		}
		w.line("  };")
		w.line("}")
		w.line("")
	}

	w.line("/** A server notification. Durable events carry seq. */")
	w.line("export type Event =")
	n := 0
	for _, f := range s.Domains {
		for _, ev := range f.Events {
			w.line(`  | { event: %q; seq?: number; data: %s }`, wireMethod(f.Domain, ev.Name), eventName(f.Domain, ev.Name))
			n++
		}
	}
	if n == 0 {
		w.line("  never")
	}
	w.line(";")
	w.line("")
	w.line("/** Every method's wire name, in schema order. */")
	w.line("export const METHODS = [")
	for _, f := range s.Domains {
		for _, m := range f.Methods {
			w.line("  %q,", wireMethod(f.Domain, m.Name))
		}
	}
	w.line("] as const;")
	w.line("")
	w.line("/** The typed maild API over a Transport. */")
	w.line("export class Client {")
	for _, f := range s.Domains {
		w.line("  readonly %s: %sClient;", f.Domain, goName(f.Domain))
	}
	w.line("")
	w.line("  constructor(readonly transport: Transport) {")
	for _, f := range s.Domains {
		w.line("    this.%s = %sClient(transport);", f.Domain, f.Domain)
	}
	w.line("  }")
	w.line("}")
	return []byte(w.String())
}

func (w *writer) tsInterface(name string, fields []Field) {
	if len(fields) == 0 {
		w.line("export type %s = Record<string, never>;", name)
		w.line("")
		return
	}
	w.line("export interface %s {", name)
	for _, f := range fields {
		w.tsdoc("  ", f.Doc)
		opt := ""
		if f.Optional {
			opt = "?"
		}
		w.line("  %s%s: %s;", f.Name, opt, tsType(f.ref))
	}
	w.line("}")
	w.line("")
}

// tsdoc writes a JSDoc comment on one line, or wrapped when long.
func (w *writer) tsdoc(indent, text string) {
	text = strings.Join(strings.Fields(text), " ")
	if text == "" {
		return
	}
	if len(indent)+len(text) <= 72 {
		w.line("%s/** %s */", indent, text)
		return
	}
	w.line("%s/**", indent)
	w.comment(indent+" * ", text)
	w.line("%s */", indent)
}

func tsType(t *TypeRef) string {
	switch {
	case t.List != nil:
		inner := tsType(t.List)
		if t.List.List != nil || t.List.Map != nil {
			inner = "(" + inner + ")"
		}
		return inner + "[]"
	case t.Map != nil:
		return "Record<string, " + tsType(t.Map) + ">"
	case t.Named != "":
		return t.Named
	}
	switch t.Prim {
	case "bool":
		return "boolean"
	case "int", "float":
		return "number"
	case "string":
		return "string"
	case "time":
		return "string /* RFC 3339 */"
	}
	return "unknown"
}

func tsResult(m Method) string {
	if m.result == nil {
		return "void"
	}
	return tsType(m.result)
}

func tsWireResult(m Method) string {
	if m.result == nil {
		return "null"
	}
	return tsType(m.result)
}

// optMark makes params optional when every field is optional.
func optMark(fields []Field) string {
	for _, f := range fields {
		if !f.Optional {
			return ""
		}
	}
	return "?"
}
