// Package api is the maild RPC contract: JSON-RPC 2.0 over a Unix socket,
// specified in docs/specs/rpc-protocol.md. zz_generated.go is generated by
// tools/rpcgen from schema/rpc; this file and its siblings are the
// hand-written runtime it relies on (Router, Client, Error and the wire types).
// Edit the schema, never the generated file.
package api

import (
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"slices"
)

// ErrorCode is a JSON-RPC error code; the generated constants name them.
type ErrorCode int

// Error is a JSON-RPC error object. Handlers return one to choose the code;
// any other error reaches the client as CodeInternal.
type Error struct {
	Code    ErrorCode      `json:"code"`
	Message string         `json:"message"`
	Data    jsontext.Value `json:"data,omitzero"`
}

// Errorf returns an *Error with a formatted message.
func Errorf(code ErrorCode, format string, args ...any) *Error {
	return &Error{Code: code, Message: fmt.Sprintf(format, args...)}
}

func (e *Error) Error() string { return fmt.Sprintf("%s: %s", e.Code, e.Message) }

// Is matches the sentinel (Err*) with the same code.
func (e *Error) Is(target error) bool {
	t, ok := target.(*Error)
	return ok && t.Code == e.Code
}

// Event is a generated event type.
type Event interface {
	EventName() string
	Durable() bool
}

// EventEnvelope is the params of an "event" notification. Seq is set for
// durable events only.
type EventEnvelope struct {
	Seq   int64          `json:"seq,omitzero"`
	Event string         `json:"event"`
	Data  jsontext.Value `json:"data"`
}

// NewEnvelope encodes ev for delivery.
func NewEnvelope(seq int64, ev Event) (EventEnvelope, error) {
	data, err := json.Marshal(ev)
	if err != nil {
		return EventEnvelope{}, fmt.Errorf("encode event %s: %w", ev.EventName(), err)
	}
	return EventEnvelope{Seq: seq, Event: ev.EventName(), Data: data}, nil
}

// handlerFunc decodes params, calls the service and returns the result.
type handlerFunc func(ctx context.Context, params jsontext.Value) (any, error)

// Router maps wire method names to service implementations.
type Router struct{ handlers map[string]handlerFunc }

// NewRouter registers every service; a nil service is an error.
func NewRouter(s Services) (*Router, error) {
	r := &Router{handlers: map[string]handlerFunc{}}
	if err := s.register(r); err != nil {
		return nil, err
	}
	return r, nil
}

func (r *Router) handle(method string, h handlerFunc) { r.handlers[method] = h }

// Dispatch runs one method. Unknown methods return ErrMethodNotFound.
func (r *Router) Dispatch(ctx context.Context, method string, params jsontext.Value) (any, error) {
	h, ok := r.handlers[method]
	if !ok {
		return nil, MethodNotFound("method %q does not exist", method)
	}
	return h(ctx, params)
}

// decodeParams strictly decodes params into p: unknown members and missing
// required members are invalidParams. Absent or null params decode as {}.
func decodeParams(raw jsontext.Value, p any, required []string) error {
	if len(raw) == 0 || string(raw) == "null" {
		raw = jsontext.Value("{}")
	}
	if raw.Kind() != '{' {
		return InvalidParams("params must be an object")
	}
	if len(required) > 0 {
		var present map[string]jsontext.Value
		if err := json.Unmarshal(raw, &present); err != nil {
			return InvalidParams("%v", err)
		}
		for _, name := range required {
			if v, ok := present[name]; !ok || string(v) == "null" {
				return InvalidParams("missing required param %q", name)
			}
		}
	}
	if err := json.Unmarshal(raw, p, json.RejectUnknownMembers(true)); err != nil {
		return InvalidParams("%v", err)
	}
	return nil
}

// HasMethod reports whether the schema defines method.
func HasMethod(method string) bool { return slices.Contains(Methods, method) }
