// Code generated by rpcgen from schema/rpc. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"time"
)

// Keep imports used when a schema has no time or json fields.
var (
	_ time.Time
	_ jsontext.Value
)

// Protocol is the protocol major version this package speaks.
const Protocol = 1

// Error codes. JSON-RPC 2.0 defines the negative codes.
const (
	// The request is not valid JSON.
	CodeParseError ErrorCode = -32700
	// The request is not a valid JSON-RPC 2.0 request object.
	CodeInvalidRequest ErrorCode = -32600
	// The method does not exist.
	CodeMethodNotFound ErrorCode = -32601
	// The params are missing, unknown or invalid.
	CodeInvalidParams ErrorCode = -32602
	// The server failed; the message says why.
	CodeInternal ErrorCode = -32603
	// The referenced entity does not exist.
	CodeNotFound ErrorCode = 1001
	// The request conflicts with existing state, such as a duplicate account.
	CodeConflict ErrorCode = 1002
	// The server does not speak the client's protocol major version.
	CodeProtocolMismatch ErrorCode = 1003
	// The connection has not completed rpc.hello.
	CodeNotReady ErrorCode = 1004
	// The operation cannot run now, for example while offline; retrying later can
	// succeed.
	CodeUnavailable ErrorCode = 1005
	// The account's credentials were rejected or have expired; the user must sign
	// in again.
	CodeAuthRequired ErrorCode = 1006
)

// Sentinels for errors.Is: an *Error matches the sentinel with its code.
var (
	ErrParseError       = &Error{Code: CodeParseError}
	ErrInvalidRequest   = &Error{Code: CodeInvalidRequest}
	ErrMethodNotFound   = &Error{Code: CodeMethodNotFound}
	ErrInvalidParams    = &Error{Code: CodeInvalidParams}
	ErrInternal         = &Error{Code: CodeInternal}
	ErrNotFound         = &Error{Code: CodeNotFound}
	ErrConflict         = &Error{Code: CodeConflict}
	ErrProtocolMismatch = &Error{Code: CodeProtocolMismatch}
	ErrNotReady         = &Error{Code: CodeNotReady}
	ErrUnavailable      = &Error{Code: CodeUnavailable}
	ErrAuthRequired     = &Error{Code: CodeAuthRequired}
)

// String is the code's schema name.
func (c ErrorCode) String() string {
	switch c {
	case CodeParseError:
		return "parseError"
	case CodeInvalidRequest:
		return "invalidRequest"
	case CodeMethodNotFound:
		return "methodNotFound"
	case CodeInvalidParams:
		return "invalidParams"
	case CodeInternal:
		return "internal"
	case CodeNotFound:
		return "notFound"
	case CodeConflict:
		return "conflict"
	case CodeProtocolMismatch:
		return "protocolMismatch"
	case CodeNotReady:
		return "notReady"
	case CodeUnavailable:
		return "unavailable"
	case CodeAuthRequired:
		return "authRequired"
	}
	return fmt.Sprintf("ErrorCode(%d)", int(c))
}

// ParseError returns an error with CodeParseError.
func ParseError(format string, args ...any) *Error { return Errorf(CodeParseError, format, args...) }

// InvalidRequest returns an error with CodeInvalidRequest.
func InvalidRequest(format string, args ...any) *Error {
	return Errorf(CodeInvalidRequest, format, args...)
}

// MethodNotFound returns an error with CodeMethodNotFound.
func MethodNotFound(format string, args ...any) *Error {
	return Errorf(CodeMethodNotFound, format, args...)
}

// InvalidParams returns an error with CodeInvalidParams.
func InvalidParams(format string, args ...any) *Error {
	return Errorf(CodeInvalidParams, format, args...)
}

// Internal returns an error with CodeInternal.
func Internal(format string, args ...any) *Error { return Errorf(CodeInternal, format, args...) }

// NotFound returns an error with CodeNotFound.
func NotFound(format string, args ...any) *Error { return Errorf(CodeNotFound, format, args...) }

// Conflict returns an error with CodeConflict.
func Conflict(format string, args ...any) *Error { return Errorf(CodeConflict, format, args...) }

// ProtocolMismatch returns an error with CodeProtocolMismatch.
func ProtocolMismatch(format string, args ...any) *Error {
	return Errorf(CodeProtocolMismatch, format, args...)
}

// NotReady returns an error with CodeNotReady.
func NotReady(format string, args ...any) *Error { return Errorf(CodeNotReady, format, args...) }

// Unavailable returns an error with CodeUnavailable.
func Unavailable(format string, args ...any) *Error { return Errorf(CodeUnavailable, format, args...) }

// AuthRequired returns an error with CodeAuthRequired.
func AuthRequired(format string, args ...any) *Error {
	return Errorf(CodeAuthRequired, format, args...)
}

// ---- account ----

// AccountKind: The provider family, which selects the sync strategy and
// server quirks.
type AccountKind string

const (
	// Generic IMAP and SMTP.
	AccountKindIMAP AccountKind = "imap"
	// Google Gmail and Workspace (labels, X-GM extensions).
	AccountKindGmail AccountKind = "gmail"
	// Microsoft 365 and Outlook.com.
	AccountKindMicrosoft AccountKind = "microsoft"
	// Apple iCloud Mail.
	AccountKindICloud AccountKind = "icloud"
)

// Valid reports whether v is one of the declared values.
func (v AccountKind) Valid() bool {
	switch v {
	case AccountKindIMAP, AccountKindGmail, AccountKindMicrosoft, AccountKindICloud:
		return true
	}
	return false
}

// AuthKind: How the account authenticates to its servers.
type AuthKind string

const (
	// A password or app-specific password, kept in the secret store.
	AuthKindPassword AuthKind = "password"
	// OAuth 2.0 tokens (SASL XOAUTH2), kept in the secret store.
	AuthKindOAuth2 AuthKind = "oauth2"
)

// Valid reports whether v is one of the declared values.
func (v AuthKind) Valid() bool {
	switch v {
	case AuthKindPassword, AuthKindOAuth2:
		return true
	}
	return false
}

// DiscoverySource: Where account.discover found server settings.
type DiscoverySource string

const (
	// Frostmail's own profile for the provider (Gmail, iCloud).
	DiscoverySourceProfile DiscoverySource = "profile"
	// The domain's Mozilla autoconfig file.
	DiscoverySourceAutoconfig DiscoverySource = "autoconfig"
	// Thunderbird's ISP database.
	DiscoverySourceIspdb DiscoverySource = "ispdb"
	// The domain's RFC 6186 SRV records.
	DiscoverySourceSrv DiscoverySource = "srv"
	// Nothing found; the user enters the servers.
	DiscoverySourceNone DiscoverySource = "none"
)

// Valid reports whether v is one of the declared values.
func (v DiscoverySource) Valid() bool {
	switch v {
	case DiscoverySourceProfile, DiscoverySourceAutoconfig, DiscoverySourceIspdb, DiscoverySourceSrv, DiscoverySourceNone:
		return true
	}
	return false
}

// TLSMode: How a connection is secured.
type TLSMode string

const (
	// TLS from the first byte (IMAPS 993, SMTPS 465).
	TLSModeTLS TLSMode = "tls"
	// Plain connection upgraded with STARTTLS (143, 587).
	TLSModeStartTLS TLSMode = "starttls"
	// No TLS. Only for local test servers.
	TLSModeInsecure TLSMode = "insecure"
)

// Valid reports whether v is one of the declared values.
func (v TLSMode) Valid() bool {
	switch v {
	case TLSModeTLS, TLSModeStartTLS, TLSModeInsecure:
		return true
	}
	return false
}

// ServerConfig: Where and how to reach one server.
type ServerConfig struct {
	Host string  `json:"host"`
	Port int64   `json:"port"`
	TLS  TLSMode `json:"tls"`
	// Login name; often the email address.
	Username string `json:"username"`
}

// Account: A configured mail account.
type Account struct {
	// Stable local identifier.
	ID   int64       `json:"id"`
	Kind AccountKind `json:"kind"`
	// The account's primary address.
	Email string `json:"email"`
	// The sender name used in From headers.
	DisplayName string       `json:"displayName"`
	Auth        AuthKind     `json:"auth"`
	IMAP        ServerConfig `json:"imap"`
	SMTP        ServerConfig `json:"smtp"`
	CreatedAt   time.Time    `json:"createdAt"`
	// maild makes no changes on the server: no flags, moves, deletes, sends or
	// draft copies.
	ReadOnly bool `json:"readOnly"`
	// New mail in the inbox shows a desktop notification.
	Notify bool `json:"notify"`
	// A password or OAuth token is stored and the server has not refused it.
	SignedIn bool `json:"signedIn"`
}

// Discovery: Server settings found for an address.
type Discovery struct {
	Kind   AccountKind     `json:"kind"`
	Source DiscoverySource `json:"source"`
	// The sign-in kinds the provider accepts, preferred first.
	Auth []AuthKind    `json:"auth"`
	IMAP *ServerConfig `json:"imap,omitzero"`
	SMTP *ServerConfig `json:"smtp,omitzero"`
}

// AuthorizeResult: An OAuth sign-in in progress.
type AuthorizeResult struct {
	// Open in the system browser; maild finishes the sign-in when the browser
	// returns.
	URL string `json:"url"`
}

// MailboxCheck: How one synced folder compares with the server.
type MailboxCheck struct {
	MailboxID int64  `json:"mailboxId"`
	Path      string `json:"path"`
	// Messages on the server.
	Server int64 `json:"server"`
	// Messages stored locally.
	Local int64 `json:"local"`
	// Server UIDs with no local message (at most 20).
	MissingLocally []int64 `json:"missingLocally"`
	// Local messages whose UID the server no longer has (at most 20).
	MissingOnServer []int64 `json:"missingOnServer"`
	// Messages whose flags differ.
	FlagDiffs int64 `json:"flagDiffs"`
	// Gmail: messages whose labels differ.
	LabelDiffs int64 `json:"labelDiffs"`
}

// VerifyReport: The result of account.verify.
type VerifyReport struct {
	AccountID int64 `json:"accountId"`
	// No folder differs.
	Ok        bool           `json:"ok"`
	Mailboxes []MailboxCheck `json:"mailboxes"`
	CheckedAt time.Time      `json:"checkedAt"`
}

// AccountListParams holds the params of account.list.
type AccountListParams struct{}

// AccountGetParams holds the params of account.get.
type AccountGetParams struct {
	ID int64 `json:"id"`
}

// AccountCreateParams holds the params of account.create.
type AccountCreateParams struct {
	Kind        AccountKind   `json:"kind"`
	Email       string        `json:"email"`
	DisplayName string        `json:"displayName"`
	Auth        AuthKind      `json:"auth"`
	IMAP        *ServerConfig `json:"imap,omitzero"`
	SMTP        *ServerConfig `json:"smtp,omitzero"`
	// Default false.
	ReadOnly *bool `json:"readOnly,omitzero"`
	// Default true.
	Notify *bool `json:"notify,omitzero"`
}

// AccountUpdateParams holds the params of account.update.
type AccountUpdateParams struct {
	ID          int64         `json:"id"`
	DisplayName *string       `json:"displayName,omitzero"`
	IMAP        *ServerConfig `json:"imap,omitzero"`
	SMTP        *ServerConfig `json:"smtp,omitzero"`
	ReadOnly    *bool         `json:"readOnly,omitzero"`
	Notify      *bool         `json:"notify,omitzero"`
}

// AccountDeleteParams holds the params of account.delete.
type AccountDeleteParams struct {
	ID int64 `json:"id"`
}

// AccountSetPasswordParams holds the params of account.setPassword.
type AccountSetPasswordParams struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

// AccountDiscoverParams holds the params of account.discover.
type AccountDiscoverParams struct {
	Email string `json:"email"`
}

// AccountAuthorizeParams holds the params of account.authorize.
type AccountAuthorizeParams struct {
	ID int64 `json:"id"`
}

// AccountVerifyParams holds the params of account.verify.
type AccountVerifyParams struct {
	ID int64 `json:"id"`
}

// AccountService: Mail accounts and their server settings. Credentials are
// write-only over RPC; account.setPassword stores one and no method returns
// it.
type AccountService interface {
	// List implements account.list. All accounts, oldest first.
	List(ctx context.Context, p *AccountListParams) ([]Account, error)
	// Get implements account.get. One account.
	Get(ctx context.Context, p *AccountGetParams) (*Account, error)
	// Create implements account.create. Add an account. The email address must be
	// unique. Gmail and iCloud accounts may leave the servers out; their profiles
	// fill them in.
	Create(ctx context.Context, p *AccountCreateParams) (*Account, error)
	// Update implements account.update. Change an account's settings. Omitted
	// fields keep their values.
	Update(ctx context.Context, p *AccountUpdateParams) (*Account, error)
	// Delete implements account.delete. Remove an account and everything stored
	// for it.
	Delete(ctx context.Context, p *AccountDeleteParams) error
	// SetPassword implements account.setPassword. Store the password (or
	// app-specific password) the account logs in with, and reconnect.
	SetPassword(ctx context.Context, p *AccountSetPasswordParams) error
	// Discover implements account.discover. Find server settings for an address
	// (provider profiles, autoconfig, the ISPDB, SRV records).
	Discover(ctx context.Context, p *AccountDiscoverParams) (*Discovery, error)
	// Authorize implements account.authorize. Start an OAuth sign-in for an
	// oauth2 account. maild listens on a loopback port for the browser's return
	// for 5 minutes, then stores the token, reconnects, and emits
	// account.changed.
	Authorize(ctx context.Context, p *AccountAuthorizeParams) (*AuthorizeResult, error)
	// Verify implements account.verify. Compare the stored mail with the server,
	// changing nothing on either side.
	Verify(ctx context.Context, p *AccountVerifyParams) (*VerifyReport, error)
}

func registerAccount(r *Router, s AccountService) {
	r.handle("account.list", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountListParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.List(ctx, &p)
	})
	r.handle("account.get", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountGetParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Get(ctx, &p)
	})
	r.handle("account.create", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountCreateParams
		if err := decodeParams(raw, &p, []string{"kind", "email", "displayName", "auth"}); err != nil {
			return nil, err
		}
		return s.Create(ctx, &p)
	})
	r.handle("account.update", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountUpdateParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Update(ctx, &p)
	})
	r.handle("account.delete", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountDeleteParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return nil, s.Delete(ctx, &p)
	})
	r.handle("account.setPassword", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountSetPasswordParams
		if err := decodeParams(raw, &p, []string{"id", "password"}); err != nil {
			return nil, err
		}
		return nil, s.SetPassword(ctx, &p)
	})
	r.handle("account.discover", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountDiscoverParams
		if err := decodeParams(raw, &p, []string{"email"}); err != nil {
			return nil, err
		}
		return s.Discover(ctx, &p)
	})
	r.handle("account.authorize", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountAuthorizeParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Authorize(ctx, &p)
	})
	r.handle("account.verify", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountVerifyParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Verify(ctx, &p)
	})
}

// AccountClient calls the account methods; it implements AccountService.
type AccountClient struct{ c *Client }

// Account returns the account methods.
func (c *Client) Account() AccountClient { return AccountClient{c} }

var _ AccountService = AccountClient{}

// List calls account.list.
func (x AccountClient) List(ctx context.Context, p *AccountListParams) ([]Account, error) {
	var r []Account
	err := x.c.Call(ctx, "account.list", p, &r)
	return r, err
}

// Get calls account.get.
func (x AccountClient) Get(ctx context.Context, p *AccountGetParams) (*Account, error) {
	var r Account
	err := x.c.Call(ctx, "account.get", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Create calls account.create.
func (x AccountClient) Create(ctx context.Context, p *AccountCreateParams) (*Account, error) {
	var r Account
	err := x.c.Call(ctx, "account.create", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Update calls account.update.
func (x AccountClient) Update(ctx context.Context, p *AccountUpdateParams) (*Account, error) {
	var r Account
	err := x.c.Call(ctx, "account.update", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Delete calls account.delete.
func (x AccountClient) Delete(ctx context.Context, p *AccountDeleteParams) error {
	return x.c.Call(ctx, "account.delete", p, nil)
}

// SetPassword calls account.setPassword.
func (x AccountClient) SetPassword(ctx context.Context, p *AccountSetPasswordParams) error {
	return x.c.Call(ctx, "account.setPassword", p, nil)
}

// Discover calls account.discover.
func (x AccountClient) Discover(ctx context.Context, p *AccountDiscoverParams) (*Discovery, error) {
	var r Discovery
	err := x.c.Call(ctx, "account.discover", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Authorize calls account.authorize.
func (x AccountClient) Authorize(ctx context.Context, p *AccountAuthorizeParams) (*AuthorizeResult, error) {
	var r AuthorizeResult
	err := x.c.Call(ctx, "account.authorize", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Verify calls account.verify.
func (x AccountClient) Verify(ctx context.Context, p *AccountVerifyParams) (*VerifyReport, error) {
	var r VerifyReport
	err := x.c.Call(ctx, "account.verify", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// AccountChanged: An account was created, updated or deleted.
type AccountChanged struct {
	ID      int64 `json:"id"`
	Deleted bool  `json:"deleted"`
}

// EventName is the wire name of AccountChanged.
func (AccountChanged) EventName() string { return "account.changed" }

// Durable reports whether AccountChanged is kept in the changes log.
func (AccountChanged) Durable() bool { return true }

// ---- address ----

// AddressSuggestParams holds the params of address.suggest.
type AddressSuggestParams struct {
	Prefix string `json:"prefix"`
	// At most this many; default 10.
	Limit *int64 `json:"limit,omitzero"`
}

// AddressService: Addresses seen in stored and sent mail, for completing
// recipients.
type AddressService interface {
	// Suggest implements address.suggest. Addresses whose address, or any word of
	// whose name, starts with prefix (case-insensitively), most used first.
	Suggest(ctx context.Context, p *AddressSuggestParams) ([]Address, error)
}

func registerAddress(r *Router, s AddressService) {
	r.handle("address.suggest", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AddressSuggestParams
		if err := decodeParams(raw, &p, []string{"prefix"}); err != nil {
			return nil, err
		}
		return s.Suggest(ctx, &p)
	})
}

// AddressClient calls the address methods; it implements AddressService.
type AddressClient struct{ c *Client }

// Address returns the address methods.
func (c *Client) Address() AddressClient { return AddressClient{c} }

var _ AddressService = AddressClient{}

// Suggest calls address.suggest.
func (x AddressClient) Suggest(ctx context.Context, p *AddressSuggestParams) ([]Address, error) {
	var r []Address
	err := x.c.Call(ctx, "address.suggest", p, &r)
	return r, err
}

// ---- draft ----

// DraftKind: How a new draft starts.
type DraftKind string

const (
	// An empty message with the identity's signature.
	DraftKindNew DraftKind = "new"
	// A reply to the source's sender.
	DraftKindReply DraftKind = "reply"
	// A reply to the sender and every other recipient but the account's own
	// addresses.
	DraftKindReplyall DraftKind = "replyall"
	// The source as quoted text with its attachments.
	DraftKindForward DraftKind = "forward"
)

// Valid reports whether v is one of the declared values.
func (v DraftKind) Valid() bool {
	switch v {
	case DraftKindNew, DraftKindReply, DraftKindReplyall, DraftKindForward:
		return true
	}
	return false
}

// DraftAttachment: A file attached to a draft, stored by maild.
type DraftAttachment struct {
	ID       int64  `json:"id"`
	Filename string `json:"filename"`
	// Lowercase type/subtype.
	ContentType string `json:"contentType"`
	// Bytes.
	Size int64 `json:"size"`
}

// DraftContent: What a compose window edits.
type DraftContent struct {
	IdentityID int64     `json:"identityId"`
	To         []Address `json:"to"`
	Cc         []Address `json:"cc"`
	Bcc        []Address `json:"bcc"`
	Subject    string    `json:"subject"`
	// The body as the editor's HTML.
	HTML string `json:"html"`
}

// Draft: A message being written.
type Draft struct {
	ID          int64             `json:"id"`
	AccountID   int64             `json:"accountId"`
	Content     DraftContent      `json:"content"`
	Attachments []DraftAttachment `json:"attachments"`
	// The message this draft replies to or forwards.
	SourceID  *int64    `json:"sourceId,omitzero"`
	Kind      DraftKind `json:"kind"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// DraftCreateParams holds the params of draft.create.
type DraftCreateParams struct {
	Kind      DraftKind `json:"kind"`
	AccountID *int64    `json:"accountId,omitzero"`
	// Required for reply, replyall and forward.
	SourceID *int64 `json:"sourceId,omitzero"`
}

// DraftOpenParams holds the params of draft.open.
type DraftOpenParams struct {
	MessageID int64 `json:"messageId"`
}

// DraftGetParams holds the params of draft.get.
type DraftGetParams struct {
	ID int64 `json:"id"`
}

// DraftListParams holds the params of draft.list.
type DraftListParams struct {
	AccountID *int64 `json:"accountId,omitzero"`
}

// DraftUpdateParams holds the params of draft.update.
type DraftUpdateParams struct {
	ID      int64        `json:"id"`
	Content DraftContent `json:"content"`
}

// DraftAttachParams holds the params of draft.attach.
type DraftAttachParams struct {
	ID int64 `json:"id"`
	// An absolute path on this machine.
	Path string `json:"path"`
}

// DraftDetachParams holds the params of draft.detach.
type DraftDetachParams struct {
	ID           int64 `json:"id"`
	AttachmentID int64 `json:"attachmentId"`
}

// DraftDeleteParams holds the params of draft.delete.
type DraftDeleteParams struct {
	ID int64 `json:"id"`
}

// DraftSendParams holds the params of draft.send.
type DraftSendParams struct {
	ID int64 `json:"id"`
}

// DraftService: Drafts: messages being written. maild stores a draft at once
// on every update and keeps a copy in the account's Drafts mailbox;
// draft.send hands it to the outbox (docs/design/send.md).
type DraftService interface {
	// Create implements draft.create. Start a draft: a new message in the account
	// (or the first account), or a reply, reply-all or forward of a message.
	Create(ctx context.Context, p *DraftCreateParams) (*Draft, error)
	// Open implements draft.open. Turn a message in a Drafts mailbox into a
	// draft, or return the draft it already is.
	Open(ctx context.Context, p *DraftOpenParams) (*Draft, error)
	// Get implements draft.get. One draft.
	Get(ctx context.Context, p *DraftGetParams) (*Draft, error)
	// List implements draft.list. Drafts, most recently changed first.
	List(ctx context.Context, p *DraftListParams) ([]Draft, error)
	// Update implements draft.update. Replace a draft's content; maild stores it
	// at once and updates the server copy later.
	Update(ctx context.Context, p *DraftUpdateParams) (*Draft, error)
	// Attach implements draft.attach. Attach a local file; maild copies it, so
	// later changes to the file do not matter.
	Attach(ctx context.Context, p *DraftAttachParams) (*DraftAttachment, error)
	// Detach implements draft.detach. Remove an attachment from a draft.
	Detach(ctx context.Context, p *DraftDetachParams) error
	// Delete implements draft.delete. Discard a draft, and its server copy.
	Delete(ctx context.Context, p *DraftDeleteParams) error
	// Send implements draft.send. Queue a draft for sending after the undo delay.
	// Fails with invalidParams when it has no recipients, an address does not
	// parse, or it is too large.
	Send(ctx context.Context, p *DraftSendParams) (*OutboxItem, error)
}

func registerDraft(r *Router, s DraftService) {
	r.handle("draft.create", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftCreateParams
		if err := decodeParams(raw, &p, []string{"kind"}); err != nil {
			return nil, err
		}
		return s.Create(ctx, &p)
	})
	r.handle("draft.open", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftOpenParams
		if err := decodeParams(raw, &p, []string{"messageId"}); err != nil {
			return nil, err
		}
		return s.Open(ctx, &p)
	})
	r.handle("draft.get", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftGetParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Get(ctx, &p)
	})
	r.handle("draft.list", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftListParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.List(ctx, &p)
	})
	r.handle("draft.update", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftUpdateParams
		if err := decodeParams(raw, &p, []string{"id", "content"}); err != nil {
			return nil, err
		}
		return s.Update(ctx, &p)
	})
	r.handle("draft.attach", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftAttachParams
		if err := decodeParams(raw, &p, []string{"id", "path"}); err != nil {
			return nil, err
		}
		return s.Attach(ctx, &p)
	})
	r.handle("draft.detach", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftDetachParams
		if err := decodeParams(raw, &p, []string{"id", "attachmentId"}); err != nil {
			return nil, err
		}
		return nil, s.Detach(ctx, &p)
	})
	r.handle("draft.delete", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftDeleteParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return nil, s.Delete(ctx, &p)
	})
	r.handle("draft.send", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p DraftSendParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Send(ctx, &p)
	})
}

// DraftClient calls the draft methods; it implements DraftService.
type DraftClient struct{ c *Client }

// Draft returns the draft methods.
func (c *Client) Draft() DraftClient { return DraftClient{c} }

var _ DraftService = DraftClient{}

// Create calls draft.create.
func (x DraftClient) Create(ctx context.Context, p *DraftCreateParams) (*Draft, error) {
	var r Draft
	err := x.c.Call(ctx, "draft.create", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Open calls draft.open.
func (x DraftClient) Open(ctx context.Context, p *DraftOpenParams) (*Draft, error) {
	var r Draft
	err := x.c.Call(ctx, "draft.open", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Get calls draft.get.
func (x DraftClient) Get(ctx context.Context, p *DraftGetParams) (*Draft, error) {
	var r Draft
	err := x.c.Call(ctx, "draft.get", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// List calls draft.list.
func (x DraftClient) List(ctx context.Context, p *DraftListParams) ([]Draft, error) {
	var r []Draft
	err := x.c.Call(ctx, "draft.list", p, &r)
	return r, err
}

// Update calls draft.update.
func (x DraftClient) Update(ctx context.Context, p *DraftUpdateParams) (*Draft, error) {
	var r Draft
	err := x.c.Call(ctx, "draft.update", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Attach calls draft.attach.
func (x DraftClient) Attach(ctx context.Context, p *DraftAttachParams) (*DraftAttachment, error) {
	var r DraftAttachment
	err := x.c.Call(ctx, "draft.attach", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Detach calls draft.detach.
func (x DraftClient) Detach(ctx context.Context, p *DraftDetachParams) error {
	return x.c.Call(ctx, "draft.detach", p, nil)
}

// Delete calls draft.delete.
func (x DraftClient) Delete(ctx context.Context, p *DraftDeleteParams) error {
	return x.c.Call(ctx, "draft.delete", p, nil)
}

// Send calls draft.send.
func (x DraftClient) Send(ctx context.Context, p *DraftSendParams) (*OutboxItem, error) {
	var r OutboxItem
	err := x.c.Call(ctx, "draft.send", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// DraftChanged: A draft was created, changed or deleted.
type DraftChanged struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountId"`
	Deleted   bool  `json:"deleted"`
}

// EventName is the wire name of DraftChanged.
func (DraftChanged) EventName() string { return "draft.changed" }

// Durable reports whether DraftChanged is kept in the changes log.
func (DraftChanged) Durable() bool { return true }

// ---- events ----

// Subscription: The state of a new subscription.
type Subscription struct {
	// The latest durable sequence number when the subscription started.
	Seq int64 `json:"seq"`
	// True when sinceSeq is older than the retained log; the client must refetch
	// all state.
	Resync bool `json:"resync"`
}

// EventsSubscribeParams holds the params of events.subscribe.
type EventsSubscribeParams struct {
	// Replay durable events after this sequence number. Omit to receive live
	// events only.
	SinceSeq *int64 `json:"sinceSeq,omitzero"`
}

// EventsService: Change notifications. After events.subscribe, the server
// sends JSON-RPC notifications with method "event" on the same connection.
// Durable events carry a sequence number and are kept in the changes log, so
// a client that reconnects can resume from the last sequence number it saw.
type EventsService interface {
	// Subscribe implements events.subscribe. Start receiving events on this
	// connection. Durable events after sinceSeq are replayed before live events.
	Subscribe(ctx context.Context, p *EventsSubscribeParams) (*Subscription, error)
}

func registerEvents(r *Router, s EventsService) {
	r.handle("events.subscribe", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p EventsSubscribeParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.Subscribe(ctx, &p)
	})
}

// EventsClient calls the events methods; it implements EventsService.
type EventsClient struct{ c *Client }

// Events returns the events methods.
func (c *Client) Events() EventsClient { return EventsClient{c} }

var _ EventsService = EventsClient{}

// Subscribe calls events.subscribe.
func (x EventsClient) Subscribe(ctx context.Context, p *EventsSubscribeParams) (*Subscription, error) {
	var r Subscription
	err := x.c.Call(ctx, "events.subscribe", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// ---- identity ----

// Identity: One From address of an account.
type Identity struct {
	ID            int64  `json:"id"`
	AccountID     int64  `json:"accountId"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	ReplyTo       string `json:"replyTo"`
	SignatureHTML string `json:"signatureHtml"`
	IsDefault     bool   `json:"isDefault"`
}

// IdentityListParams holds the params of identity.list.
type IdentityListParams struct {
	AccountID *int64 `json:"accountId,omitzero"`
}

// IdentityUpdateParams holds the params of identity.update.
type IdentityUpdateParams struct {
	ID            int64   `json:"id"`
	Name          *string `json:"name,omitzero"`
	ReplyTo       *string `json:"replyTo,omitzero"`
	SignatureHTML *string `json:"signatureHtml,omitzero"`
}

// IdentityService: The addresses an account sends as, with their signatures.
type IdentityService interface {
	// List implements identity.list. Identities, default first per account.
	List(ctx context.Context, p *IdentityListParams) ([]Identity, error)
	// Update implements identity.update. Change an identity's name, Reply-To or
	// signature.
	Update(ctx context.Context, p *IdentityUpdateParams) (*Identity, error)
}

func registerIdentity(r *Router, s IdentityService) {
	r.handle("identity.list", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p IdentityListParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.List(ctx, &p)
	})
	r.handle("identity.update", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p IdentityUpdateParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Update(ctx, &p)
	})
}

// IdentityClient calls the identity methods; it implements IdentityService.
type IdentityClient struct{ c *Client }

// Identity returns the identity methods.
func (c *Client) Identity() IdentityClient { return IdentityClient{c} }

var _ IdentityService = IdentityClient{}

// List calls identity.list.
func (x IdentityClient) List(ctx context.Context, p *IdentityListParams) ([]Identity, error) {
	var r []Identity
	err := x.c.Call(ctx, "identity.list", p, &r)
	return r, err
}

// Update calls identity.update.
func (x IdentityClient) Update(ctx context.Context, p *IdentityUpdateParams) (*Identity, error) {
	var r Identity
	err := x.c.Call(ctx, "identity.update", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// ---- mailbox ----

// MailboxRole: What a mailbox is for, from SPECIAL-USE attributes or name
// heuristics.
type MailboxRole string

const (
	// An ordinary user folder.
	MailboxRoleNone    MailboxRole = "none"
	MailboxRoleInbox   MailboxRole = "inbox"
	MailboxRoleDrafts  MailboxRole = "drafts"
	MailboxRoleSent    MailboxRole = "sent"
	MailboxRoleArchive MailboxRole = "archive"
	MailboxRoleJunk    MailboxRole = "junk"
	MailboxRoleTrash   MailboxRole = "trash"
	// All messages (Gmail All Mail).
	MailboxRoleAll MailboxRole = "all"
	// A server-side flagged view (Gmail Starred).
	MailboxRoleFlagged MailboxRole = "flagged"
)

// Valid reports whether v is one of the declared values.
func (v MailboxRole) Valid() bool {
	switch v {
	case MailboxRoleNone, MailboxRoleInbox, MailboxRoleDrafts, MailboxRoleSent, MailboxRoleArchive, MailboxRoleJunk, MailboxRoleTrash, MailboxRoleAll, MailboxRoleFlagged:
		return true
	}
	return false
}

// Mailbox: One mailbox of one account.
type Mailbox struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountId"`
	// Full server path, decoded from modified UTF-7.
	Path string `json:"path"`
	// The last path component, for display.
	Name string `json:"name"`
	// The server's hierarchy delimiter; empty when flat.
	Delimiter string      `json:"delimiter"`
	Role      MailboxRole `json:"role"`
	// Messages stored locally for this mailbox.
	Total int64 `json:"total"`
	// Unread messages stored locally for this mailbox.
	Unread int64 `json:"unread"`
	// A Gmail label: a message can be in several labels at once, moving it out of
	// one removes only that label, and All Mail is where Archive moves to.
	Label bool `json:"label"`
}

// MailboxListParams holds the params of mailbox.list.
type MailboxListParams struct {
	// Limit to one account. Omit for all accounts.
	AccountID *int64 `json:"accountId,omitzero"`
}

// MailboxService: Mailboxes (IMAP folders, and Gmail labels shown as
// folders).
type MailboxService interface {
	// List implements mailbox.list. Mailboxes ordered by account, role, then
	// path.
	List(ctx context.Context, p *MailboxListParams) ([]Mailbox, error)
}

func registerMailbox(r *Router, s MailboxService) {
	r.handle("mailbox.list", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MailboxListParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.List(ctx, &p)
	})
}

// MailboxClient calls the mailbox methods; it implements MailboxService.
type MailboxClient struct{ c *Client }

// Mailbox returns the mailbox methods.
func (c *Client) Mailbox() MailboxClient { return MailboxClient{c} }

var _ MailboxService = MailboxClient{}

// List calls mailbox.list.
func (x MailboxClient) List(ctx context.Context, p *MailboxListParams) ([]Mailbox, error) {
	var r []Mailbox
	err := x.c.Call(ctx, "mailbox.list", p, &r)
	return r, err
}

// MailboxChanged: A mailbox was created, renamed, deleted, or its counts
// changed.
type MailboxChanged struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountId"`
	Deleted   bool  `json:"deleted"`
}

// EventName is the wire name of MailboxChanged.
func (MailboxChanged) EventName() string { return "mailbox.changed" }

// Durable reports whether MailboxChanged is kept in the changes log.
func (MailboxChanged) Durable() bool { return true }

// ---- message ----

// Address: One mailbox address.
type Address struct {
	// Display name; may be empty.
	Name    string `json:"name"`
	Address string `json:"address"`
}

// Flags: The flags clients show and change.
type Flags struct {
	Seen      bool `json:"seen"`
	Flagged   bool `json:"flagged"`
	Answered  bool `json:"answered"`
	Forwarded bool `json:"forwarded"`
	Draft     bool `json:"draft"`
	// 0 for none, 1-7 for Mail.app's flag colors (stored as $MailFlagBit0-2).
	FlagColor int64 `json:"flagColor"`
}

// MessageSummary: A row of a message list.
type MessageSummary struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountId"`
	// Mailboxes holding the message: one for IMAP, one per label for Gmail.
	MailboxIDs []int64 `json:"mailboxIds"`
	ThreadID   int64   `json:"threadId"`
	Subject    string  `json:"subject"`
	From       Address `json:"from"`
	// The Date header, or the server's arrival time when Date is missing or
	// invalid.
	Date time.Time `json:"date"`
	// The first lines of the text, without quotes or signature.
	Preview        string `json:"preview"`
	Flags          Flags  `json:"flags"`
	HasAttachments bool   `json:"hasAttachments"`
	// Size in bytes on the server.
	Size int64 `json:"size"`
	// Messages in the thread across every mailbox; 1 for a message alone.
	ThreadCount int64 `json:"threadCount"`
}

// Part: One MIME part.
type Part struct {
	// IMAP part specifier, such as 1 or 1.2.
	Path string `json:"path"`
	// Lowercase type/subtype.
	ContentType string `json:"contentType"`
	Filename    string `json:"filename"`
	// inline, attachment or empty.
	Disposition string `json:"disposition"`
	// Without angle brackets.
	ContentID string `json:"contentId"`
	// Encoded size in bytes.
	Size int64 `json:"size"`
}

// Message: Everything about a message except its body.
type Message struct {
	Summary MessageSummary `json:"summary"`
	To      []Address      `json:"to"`
	Cc      []Address      `json:"cc"`
	ReplyTo []Address      `json:"replyTo"`
	// Message-ID without angle brackets.
	MessageID       string   `json:"messageId"`
	InReplyTo       string   `json:"inReplyTo"`
	References      []string `json:"references"`
	ListID          string   `json:"listId"`
	ListUnsubscribe string   `json:"listUnsubscribe"`
	Parts           []Part   `json:"parts"`
	// Whether the full message is stored locally.
	BodyFetched bool `json:"bodyFetched"`
}

// Body: A message's readable text.
type Body struct {
	// The text/plain part, or text derived from the HTML part.
	Text string `json:"text"`
	// Whether an HTML part exists (rendered from M2 on).
	HasHTML bool `json:"hasHtml"`
}

// Rendering: A message prepared for the reader.
type Rendering struct {
	// Sanitized HTML for the sandboxed reader frame, or empty for a text-only
	// message. Parts and loaded remote images are mailpart://localhost/ URLs.
	HTML string `json:"html"`
	// The readable text, as message.body returns it.
	Text string `json:"text"`
	// Remote resources left out: not requested, or requested and failed.
	Remote int64 `json:"remote"`
	// Tracking images removed; they are never loaded.
	Trackers int64 `json:"trackers"`
}

// PartFile: A message part decoded into the parts cache.
type PartFile struct {
	// Relative to the parts cache, as in a mailpart://localhost/ URL.
	Path string `json:"path"`
	// Lowercase type/subtype.
	ContentType string `json:"contentType"`
	// A safe file name: the part's, or one made from its type.
	Filename string `json:"filename"`
	// Decoded size in bytes.
	Size int64 `json:"size"`
}

// FlagChanges: Flags to set or clear; omitted fields keep their values.
type FlagChanges struct {
	Seen      *bool  `json:"seen,omitzero"`
	Flagged   *bool  `json:"flagged,omitzero"`
	Answered  *bool  `json:"answered,omitzero"`
	FlagColor *int64 `json:"flagColor,omitzero"`
}

// MessageGetParams holds the params of message.get.
type MessageGetParams struct {
	ID int64 `json:"id"`
}

// MessageBodyParams holds the params of message.body.
type MessageBodyParams struct {
	ID int64 `json:"id"`
}

// MessageSummariesParams holds the params of message.summaries.
type MessageSummariesParams struct {
	IDs []int64 `json:"ids"`
}

// MessageRenderParams holds the params of message.render.
type MessageRenderParams struct {
	ID     int64 `json:"id"`
	Remote *bool `json:"remote,omitzero"`
}

// MessagePartParams holds the params of message.part.
type MessagePartParams struct {
	ID int64 `json:"id"`
	// The part's IMAP specifier from Message.parts.
	Path string `json:"path"`
}

// MessageSetFlagsParams holds the params of message.setFlags.
type MessageSetFlagsParams struct {
	IDs     []int64     `json:"ids"`
	Changes FlagChanges `json:"changes"`
}

// MessageMoveParams holds the params of message.move.
type MessageMoveParams struct {
	IDs       []int64 `json:"ids"`
	MailboxID int64   `json:"mailboxId"`
	// The mailbox the messages leave, where a message can be in several (Gmail
	// labels): moving out of a label removes that label only. Omit for the
	// mailbox that holds them; for Gmail that is INBOX when they are in it.
	FromMailboxID *int64 `json:"fromMailboxId,omitzero"`
}

// MessageDeleteParams holds the params of message.delete.
type MessageDeleteParams struct {
	IDs []int64 `json:"ids"`
}

// MessageService: Messages. An ID is local and stays the same while the
// message exists, including across moves the server reports with COPYUID.
type MessageService interface {
	// Get implements message.get. One message's headers and structure.
	Get(ctx context.Context, p *MessageGetParams) (*Message, error)
	// Body implements message.body. A message's text, fetching the message from
	// the server first if it is not stored locally.
	Body(ctx context.Context, p *MessageBodyParams) (*Body, error)
	// Summaries implements message.summaries. Summaries of messages in the order
	// given; IDs that no longer exist are skipped.
	Summaries(ctx context.Context, p *MessageSummariesParams) ([]MessageSummary, error)
	// Render implements message.render. A message prepared for the reader,
	// fetching it first if it is not stored locally. Remote images are loaded
	// through maild only when remote is true; tracking images never are.
	Render(ctx context.Context, p *MessageRenderParams) (*Rendering, error)
	// Part implements message.part. Decode one part (an attachment or inline
	// image) into the parts cache.
	Part(ctx context.Context, p *MessagePartParams) (*PartFile, error)
	// SetFlags implements message.setFlags. Change flags locally at once and on
	// the server when it can be reached.
	SetFlags(ctx context.Context, p *MessageSetFlagsParams) error
	// Move implements message.move. Move messages to another mailbox of the same
	// account.
	Move(ctx context.Context, p *MessageMoveParams) error
	// Delete implements message.delete. Move messages to the account's Trash;
	// messages already in Trash are deleted from the server.
	Delete(ctx context.Context, p *MessageDeleteParams) error
}

func registerMessage(r *Router, s MessageService) {
	r.handle("message.get", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MessageGetParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Get(ctx, &p)
	})
	r.handle("message.body", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MessageBodyParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Body(ctx, &p)
	})
	r.handle("message.summaries", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MessageSummariesParams
		if err := decodeParams(raw, &p, []string{"ids"}); err != nil {
			return nil, err
		}
		return s.Summaries(ctx, &p)
	})
	r.handle("message.render", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MessageRenderParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Render(ctx, &p)
	})
	r.handle("message.part", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MessagePartParams
		if err := decodeParams(raw, &p, []string{"id", "path"}); err != nil {
			return nil, err
		}
		return s.Part(ctx, &p)
	})
	r.handle("message.setFlags", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MessageSetFlagsParams
		if err := decodeParams(raw, &p, []string{"ids", "changes"}); err != nil {
			return nil, err
		}
		return nil, s.SetFlags(ctx, &p)
	})
	r.handle("message.move", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MessageMoveParams
		if err := decodeParams(raw, &p, []string{"ids", "mailboxId"}); err != nil {
			return nil, err
		}
		return nil, s.Move(ctx, &p)
	})
	r.handle("message.delete", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MessageDeleteParams
		if err := decodeParams(raw, &p, []string{"ids"}); err != nil {
			return nil, err
		}
		return nil, s.Delete(ctx, &p)
	})
}

// MessageClient calls the message methods; it implements MessageService.
type MessageClient struct{ c *Client }

// Message returns the message methods.
func (c *Client) Message() MessageClient { return MessageClient{c} }

var _ MessageService = MessageClient{}

// Get calls message.get.
func (x MessageClient) Get(ctx context.Context, p *MessageGetParams) (*Message, error) {
	var r Message
	err := x.c.Call(ctx, "message.get", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Body calls message.body.
func (x MessageClient) Body(ctx context.Context, p *MessageBodyParams) (*Body, error) {
	var r Body
	err := x.c.Call(ctx, "message.body", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Summaries calls message.summaries.
func (x MessageClient) Summaries(ctx context.Context, p *MessageSummariesParams) ([]MessageSummary, error) {
	var r []MessageSummary
	err := x.c.Call(ctx, "message.summaries", p, &r)
	return r, err
}

// Render calls message.render.
func (x MessageClient) Render(ctx context.Context, p *MessageRenderParams) (*Rendering, error) {
	var r Rendering
	err := x.c.Call(ctx, "message.render", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Part calls message.part.
func (x MessageClient) Part(ctx context.Context, p *MessagePartParams) (*PartFile, error) {
	var r PartFile
	err := x.c.Call(ctx, "message.part", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// SetFlags calls message.setFlags.
func (x MessageClient) SetFlags(ctx context.Context, p *MessageSetFlagsParams) error {
	return x.c.Call(ctx, "message.setFlags", p, nil)
}

// Move calls message.move.
func (x MessageClient) Move(ctx context.Context, p *MessageMoveParams) error {
	return x.c.Call(ctx, "message.move", p, nil)
}

// Delete calls message.delete.
func (x MessageClient) Delete(ctx context.Context, p *MessageDeleteParams) error {
	return x.c.Call(ctx, "message.delete", p, nil)
}

// MessageChanged: Messages were added or changed (flags, mailbox, fetched
// body).
type MessageChanged struct {
	AccountID int64   `json:"accountId"`
	IDs       []int64 `json:"ids"`
}

// EventName is the wire name of MessageChanged.
func (MessageChanged) EventName() string { return "message.changed" }

// Durable reports whether MessageChanged is kept in the changes log.
func (MessageChanged) Durable() bool { return true }

// MessageRemoved: Messages no longer exist locally.
type MessageRemoved struct {
	AccountID int64   `json:"accountId"`
	IDs       []int64 `json:"ids"`
}

// EventName is the wire name of MessageRemoved.
func (MessageRemoved) EventName() string { return "message.removed" }

// Durable reports whether MessageRemoved is kept in the changes log.
func (MessageRemoved) Durable() bool { return true }

// ---- oauth ----

// OAuthProvider: An OAuth identity provider maild knows the endpoints of.
type OAuthProvider string

const (
	// Google accounts (Gmail).
	OAuthProviderGoogle OAuthProvider = "google"
	// Microsoft accounts (not yet used).
	OAuthProviderMicrosoft OAuthProvider = "microsoft"
)

// Valid reports whether v is one of the declared values.
func (v OAuthProvider) Valid() bool {
	switch v {
	case OAuthProviderGoogle, OAuthProviderMicrosoft:
		return true
	}
	return false
}

// OAuthClient: A registered OAuth client.
type OAuthClient struct {
	Provider OAuthProvider `json:"provider"`
	ClientID string        `json:"clientId"`
	// A client secret is stored.
	HasSecret bool `json:"hasSecret"`
}

// OauthSetClientParams holds the params of oauth.setClient.
type OauthSetClientParams struct {
	Provider OAuthProvider `json:"provider"`
	ClientID string        `json:"clientId"`
	// Desktop clients have one; it is kept in the secret store.
	ClientSecret *string `json:"clientSecret,omitzero"`
}

// OauthGetClientParams holds the params of oauth.getClient.
type OauthGetClientParams struct {
	Provider OAuthProvider `json:"provider"`
}

// OauthService: The OAuth clients maild signs in with. Until Frostmail ships
// verified clients (M6) the user registers their own
// (docs/design/accounts.md). The client secret is write-only.
type OauthService interface {
	// SetClient implements oauth.setClient. Store the client maild signs in to a
	// provider with, replacing any previous one.
	SetClient(ctx context.Context, p *OauthSetClientParams) (*OAuthClient, error)
	// GetClient implements oauth.getClient. The client stored for a provider.
	GetClient(ctx context.Context, p *OauthGetClientParams) (*OAuthClient, error)
}

func registerOauth(r *Router, s OauthService) {
	r.handle("oauth.setClient", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p OauthSetClientParams
		if err := decodeParams(raw, &p, []string{"provider", "clientId"}); err != nil {
			return nil, err
		}
		return s.SetClient(ctx, &p)
	})
	r.handle("oauth.getClient", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p OauthGetClientParams
		if err := decodeParams(raw, &p, []string{"provider"}); err != nil {
			return nil, err
		}
		return s.GetClient(ctx, &p)
	})
}

// OauthClient calls the oauth methods; it implements OauthService.
type OauthClient struct{ c *Client }

// Oauth returns the oauth methods.
func (c *Client) Oauth() OauthClient { return OauthClient{c} }

var _ OauthService = OauthClient{}

// SetClient calls oauth.setClient.
func (x OauthClient) SetClient(ctx context.Context, p *OauthSetClientParams) (*OAuthClient, error) {
	var r OAuthClient
	err := x.c.Call(ctx, "oauth.setClient", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// GetClient calls oauth.getClient.
func (x OauthClient) GetClient(ctx context.Context, p *OauthGetClientParams) (*OAuthClient, error) {
	var r OAuthClient
	err := x.c.Call(ctx, "oauth.getClient", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// ---- outbox ----

// OutboxState: Where a message is on its way out.
type OutboxState string

const (
	// Waiting for its send time: the undo delay, or a retry after an error.
	OutboxStateQueued OutboxState = "queued"
	// Being handed to the SMTP server.
	OutboxStateSending OutboxState = "sending"
	// The SMTP server took it; the Sent copy is being saved.
	OutboxStateAccepted OutboxState = "accepted"
	// Done.
	OutboxStateSent OutboxState = "sent"
	// The server refused it; the draft is kept.
	OutboxStateFailed OutboxState = "failed"
)

// Valid reports whether v is one of the declared values.
func (v OutboxState) Valid() bool {
	switch v {
	case OutboxStateQueued, OutboxStateSending, OutboxStateAccepted, OutboxStateSent, OutboxStateFailed:
		return true
	}
	return false
}

// OutboxItem: One message on its way out.
type OutboxItem struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountId"`
	// Set until the message is accepted.
	DraftID *int64      `json:"draftId,omitzero"`
	Subject string      `json:"subject"`
	To      []Address   `json:"to"`
	State   OutboxState `json:"state"`
	// When a queued message goes out.
	SendAt   *time.Time `json:"sendAt,omitzero"`
	Attempts int64      `json:"attempts"`
	// The last error, when there was one.
	Error *string `json:"error,omitzero"`
}

// OutboxListParams holds the params of outbox.list.
type OutboxListParams struct {
	AccountID *int64 `json:"accountId,omitzero"`
}

// OutboxCancelParams holds the params of outbox.cancel.
type OutboxCancelParams struct {
	ID int64 `json:"id"`
}

// OutboxRetryParams holds the params of outbox.retry.
type OutboxRetryParams struct {
	ID int64 `json:"id"`
}

// OutboxService: Messages on their way out (docs/design/send.md, Outbox).
type OutboxService interface {
	// List implements outbox.list. Messages not yet sent, oldest first.
	List(ctx context.Context, p *OutboxListParams) ([]OutboxItem, error)
	// Cancel implements outbox.cancel. Stop a queued message (undo send) and
	// return its draft.
	Cancel(ctx context.Context, p *OutboxCancelParams) (*Draft, error)
	// Retry implements outbox.retry. Queue a failed message again, now.
	Retry(ctx context.Context, p *OutboxRetryParams) error
}

func registerOutbox(r *Router, s OutboxService) {
	r.handle("outbox.list", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p OutboxListParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.List(ctx, &p)
	})
	r.handle("outbox.cancel", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p OutboxCancelParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Cancel(ctx, &p)
	})
	r.handle("outbox.retry", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p OutboxRetryParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return nil, s.Retry(ctx, &p)
	})
}

// OutboxClient calls the outbox methods; it implements OutboxService.
type OutboxClient struct{ c *Client }

// Outbox returns the outbox methods.
func (c *Client) Outbox() OutboxClient { return OutboxClient{c} }

var _ OutboxService = OutboxClient{}

// List calls outbox.list.
func (x OutboxClient) List(ctx context.Context, p *OutboxListParams) ([]OutboxItem, error) {
	var r []OutboxItem
	err := x.c.Call(ctx, "outbox.list", p, &r)
	return r, err
}

// Cancel calls outbox.cancel.
func (x OutboxClient) Cancel(ctx context.Context, p *OutboxCancelParams) (*Draft, error) {
	var r Draft
	err := x.c.Call(ctx, "outbox.cancel", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Retry calls outbox.retry.
func (x OutboxClient) Retry(ctx context.Context, p *OutboxRetryParams) error {
	return x.c.Call(ctx, "outbox.retry", p, nil)
}

// OutboxChanged: An outbox message changed state.
type OutboxChanged struct {
	ID        int64       `json:"id"`
	AccountID int64       `json:"accountId"`
	State     OutboxState `json:"state"`
	// The message left the outbox unsent: cancelled, or replaced by a new send of
	// its draft.
	Deleted bool `json:"deleted"`
}

// EventName is the wire name of OutboxChanged.
func (OutboxChanged) EventName() string { return "outbox.changed" }

// Durable reports whether OutboxChanged is kept in the changes log.
func (OutboxChanged) Durable() bool { return true }

// ---- rpc ----

// Hello: Server identity and the negotiated protocol.
type Hello struct {
	// Protocol major version the server speaks.
	Protocol int64 `json:"protocol"`
	// Server name and version, for logs.
	Server string `json:"server"`
}

// RPCHelloParams holds the params of rpc.hello.
type RPCHelloParams struct {
	// Protocol major version the client speaks.
	Protocol int64 `json:"protocol"`
	// Client name and version, for logs.
	Client string `json:"client"`
}

// RPCService: Connection setup. A client calls rpc.hello first on every
// connection; the server answers any other method with notReady until hello
// succeeds.
type RPCService interface {
	// Hello implements rpc.hello. Negotiate the protocol major version. Changes
	// within a major version are additive only.
	Hello(ctx context.Context, p *RPCHelloParams) (*Hello, error)
}

func registerRPC(r *Router, s RPCService) {
	r.handle("rpc.hello", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p RPCHelloParams
		if err := decodeParams(raw, &p, []string{"protocol", "client"}); err != nil {
			return nil, err
		}
		return s.Hello(ctx, &p)
	})
}

// RPCClient calls the rpc methods; it implements RPCService.
type RPCClient struct{ c *Client }

// RPC returns the rpc methods.
func (c *Client) RPC() RPCClient { return RPCClient{c} }

var _ RPCService = RPCClient{}

// Hello calls rpc.hello.
func (x RPCClient) Hello(ctx context.Context, p *RPCHelloParams) (*Hello, error) {
	var r Hello
	err := x.c.Call(ctx, "rpc.hello", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// ---- sync ----

// SyncPhase: What an account's sync is doing.
type SyncPhase string

const (
	// Up to date and watching for changes.
	SyncPhaseIdle SyncPhase = "idle"
	// Connecting and logging in.
	SyncPhaseConnecting SyncPhase = "connecting"
	// Listing mailboxes.
	SyncPhaseListing SyncPhase = "listing"
	// Reconciling mailboxes with the server.
	SyncPhaseSyncing SyncPhase = "syncing"
	// The server cannot be reached; retrying with backoff.
	SyncPhaseOffline SyncPhase = "offline"
	// The server rejected the credentials; account.setPassword retries.
	SyncPhaseUnauthorized SyncPhase = "unauthorized"
	// An unexpected error stopped sync; the error field says why. Retried with
	// backoff.
	SyncPhaseFailed SyncPhase = "failed"
)

// Valid reports whether v is one of the declared values.
func (v SyncPhase) Valid() bool {
	switch v {
	case SyncPhaseIdle, SyncPhaseConnecting, SyncPhaseListing, SyncPhaseSyncing, SyncPhaseOffline, SyncPhaseUnauthorized, SyncPhaseFailed:
		return true
	}
	return false
}

// SyncStatus: One account's sync state.
type SyncStatus struct {
	AccountID int64     `json:"accountId"`
	Phase     SyncPhase `json:"phase"`
	// The mailbox path being synced, while syncing.
	Mailbox *string `json:"mailbox,omitzero"`
	// Progress within the phase; 0 with total 0 when unknown.
	Done  int64   `json:"done"`
	Total int64   `json:"total"`
	Error *string `json:"error,omitzero"`
	// When every mailbox was last reconciled.
	LastSyncAt *time.Time `json:"lastSyncAt,omitzero"`
}

// SyncStatusParams holds the params of sync.status.
type SyncStatusParams struct {
	AccountID *int64 `json:"accountId,omitzero"`
}

// SyncNowParams holds the params of sync.now.
type SyncNowParams struct {
	AccountID int64 `json:"accountId"`
}

// SyncService: Account synchronization state and control.
type SyncService interface {
	// Status implements sync.status. The sync state of every account, or of one.
	Status(ctx context.Context, p *SyncStatusParams) ([]SyncStatus, error)
	// Now implements sync.now. Reconcile every mailbox of the account now instead
	// of at the next poll.
	Now(ctx context.Context, p *SyncNowParams) error
}

func registerSync(r *Router, s SyncService) {
	r.handle("sync.status", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p SyncStatusParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.Status(ctx, &p)
	})
	r.handle("sync.now", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p SyncNowParams
		if err := decodeParams(raw, &p, []string{"accountId"}); err != nil {
			return nil, err
		}
		return nil, s.Now(ctx, &p)
	})
}

// SyncClient calls the sync methods; it implements SyncService.
type SyncClient struct{ c *Client }

// Sync returns the sync methods.
func (c *Client) Sync() SyncClient { return SyncClient{c} }

var _ SyncService = SyncClient{}

// Status calls sync.status.
func (x SyncClient) Status(ctx context.Context, p *SyncStatusParams) ([]SyncStatus, error) {
	var r []SyncStatus
	err := x.c.Call(ctx, "sync.status", p, &r)
	return r, err
}

// Now calls sync.now.
func (x SyncClient) Now(ctx context.Context, p *SyncNowParams) error {
	return x.c.Call(ctx, "sync.now", p, nil)
}

// SyncProgress: An account's sync state changed.
type SyncProgress struct {
	Status SyncStatus `json:"status"`
}

// EventName is the wire name of SyncProgress.
func (SyncProgress) EventName() string { return "sync.progress" }

// Durable reports whether SyncProgress is kept in the changes log.
func (SyncProgress) Durable() bool { return false }

// ---- thread ----

// ThreadMessagesParams holds the params of thread.messages.
type ThreadMessagesParams struct {
	ID int64 `json:"id"`
}

// ThreadService: Conversations, built by maild from message references (Gmail
// threads on Gmail).
type ThreadService interface {
	// Messages implements thread.messages. The messages of a thread in every
	// mailbox, oldest first, without messages deleted locally.
	Messages(ctx context.Context, p *ThreadMessagesParams) ([]MessageSummary, error)
}

func registerThread(r *Router, s ThreadService) {
	r.handle("thread.messages", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p ThreadMessagesParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Messages(ctx, &p)
	})
}

// ThreadClient calls the thread methods; it implements ThreadService.
type ThreadClient struct{ c *Client }

// Thread returns the thread methods.
func (c *Client) Thread() ThreadClient { return ThreadClient{c} }

var _ ThreadService = ThreadClient{}

// Messages calls thread.messages.
func (x ThreadClient) Messages(ctx context.Context, p *ThreadMessagesParams) ([]MessageSummary, error) {
	var r []MessageSummary
	err := x.c.Call(ctx, "thread.messages", p, &r)
	return r, err
}

// ---- view ----

// ViewOpKind: How a delta changes a view.
type ViewOpKind string

const (
	// count rows were inserted at index at.
	ViewOpKindInsert ViewOpKind = "insert"
	// count rows starting at index at were removed.
	ViewOpKindRemove ViewOpKind = "remove"
)

// Valid reports whether v is one of the declared values.
func (v ViewOpKind) Valid() bool {
	switch v {
	case ViewOpKindInsert, ViewOpKindRemove:
		return true
	}
	return false
}

// ViewQuery: Which messages a view lists, newest first. Every field that is
// set must match.
type ViewQuery struct {
	AccountID *int64 `json:"accountId,omitzero"`
	MailboxID *int64 `json:"mailboxId,omitzero"`
	// Full-text search terms.
	Text    *string `json:"text,omitzero"`
	Unread  *bool   `json:"unread,omitzero"`
	Flagged *bool   `json:"flagged,omitzero"`
	// Messages in mailboxes with this role in any account, such as every inbox.
	Role *MailboxRole `json:"role,omitzero"`
	// One row per thread: its newest message that matches.
	Threads *bool `json:"threads,omitzero"`
}

// ViewInfo: An open view.
type ViewInfo struct {
	ID    int64 `json:"id"`
	Count int64 `json:"count"`
}

// ViewOp: One step of a delta; apply a delta's ops in order.
type ViewOp struct {
	Op    ViewOpKind `json:"op"`
	At    int64      `json:"at"`
	Count int64      `json:"count"`
}

// ViewOpenParams holds the params of view.open.
type ViewOpenParams struct {
	Query ViewQuery `json:"query"`
}

// ViewRangeParams holds the params of view.range.
type ViewRangeParams struct {
	ID    int64 `json:"id"`
	Start int64 `json:"start"`
	End   int64 `json:"end"`
}

// ViewCloseParams holds the params of view.close.
type ViewCloseParams struct {
	ID int64 `json:"id"`
}

// ViewService: Live message lists. A view belongs to the connection that
// opened it, sends its deltas only there, and closes with it.
type ViewService interface {
	// Open implements view.open. Open a view; deltas follow on this connection
	// without events.subscribe.
	Open(ctx context.Context, p *ViewOpenParams) (*ViewInfo, error)
	// Range implements view.range. The rows from start up to, not including, end;
	// end is capped at the view's count.
	Range(ctx context.Context, p *ViewRangeParams) ([]MessageSummary, error)
	// Close implements view.close. Close a view.
	Close(ctx context.Context, p *ViewCloseParams) error
}

func registerView(r *Router, s ViewService) {
	r.handle("view.open", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p ViewOpenParams
		if err := decodeParams(raw, &p, []string{"query"}); err != nil {
			return nil, err
		}
		return s.Open(ctx, &p)
	})
	r.handle("view.range", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p ViewRangeParams
		if err := decodeParams(raw, &p, []string{"id", "start", "end"}); err != nil {
			return nil, err
		}
		return s.Range(ctx, &p)
	})
	r.handle("view.close", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p ViewCloseParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return nil, s.Close(ctx, &p)
	})
}

// ViewClient calls the view methods; it implements ViewService.
type ViewClient struct{ c *Client }

// View returns the view methods.
func (c *Client) View() ViewClient { return ViewClient{c} }

var _ ViewService = ViewClient{}

// Open calls view.open.
func (x ViewClient) Open(ctx context.Context, p *ViewOpenParams) (*ViewInfo, error) {
	var r ViewInfo
	err := x.c.Call(ctx, "view.open", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Range calls view.range.
func (x ViewClient) Range(ctx context.Context, p *ViewRangeParams) ([]MessageSummary, error) {
	var r []MessageSummary
	err := x.c.Call(ctx, "view.range", p, &r)
	return r, err
}

// Close calls view.close.
func (x ViewClient) Close(ctx context.Context, p *ViewCloseParams) error {
	return x.c.Call(ctx, "view.close", p, nil)
}

// ViewDelta: A view's rows changed. Rows a client holds are moved by the ops;
// fetch inserted rows with view.range.
type ViewDelta struct {
	ID int64 `json:"id"`
	// The row count after the ops.
	Count int64    `json:"count"`
	Ops   []ViewOp `json:"ops"`
}

// EventName is the wire name of ViewDelta.
func (ViewDelta) EventName() string { return "view.delta" }

// Durable reports whether ViewDelta is kept in the changes log.
func (ViewDelta) Durable() bool { return false }

// Services is one implementation per domain, for NewRouter.
type Services struct {
	Account  AccountService
	Address  AddressService
	Draft    DraftService
	Events   EventsService
	Identity IdentityService
	Mailbox  MailboxService
	Message  MessageService
	Oauth    OauthService
	Outbox   OutboxService
	RPC      RPCService
	Sync     SyncService
	Thread   ThreadService
	View     ViewService
}

func (s Services) register(r *Router) error {
	if s.Account == nil {
		return errors.New("api: Services.Account is nil")
	}
	registerAccount(r, s.Account)
	if s.Address == nil {
		return errors.New("api: Services.Address is nil")
	}
	registerAddress(r, s.Address)
	if s.Draft == nil {
		return errors.New("api: Services.Draft is nil")
	}
	registerDraft(r, s.Draft)
	if s.Events == nil {
		return errors.New("api: Services.Events is nil")
	}
	registerEvents(r, s.Events)
	if s.Identity == nil {
		return errors.New("api: Services.Identity is nil")
	}
	registerIdentity(r, s.Identity)
	if s.Mailbox == nil {
		return errors.New("api: Services.Mailbox is nil")
	}
	registerMailbox(r, s.Mailbox)
	if s.Message == nil {
		return errors.New("api: Services.Message is nil")
	}
	registerMessage(r, s.Message)
	if s.Oauth == nil {
		return errors.New("api: Services.Oauth is nil")
	}
	registerOauth(r, s.Oauth)
	if s.Outbox == nil {
		return errors.New("api: Services.Outbox is nil")
	}
	registerOutbox(r, s.Outbox)
	if s.RPC == nil {
		return errors.New("api: Services.RPC is nil")
	}
	registerRPC(r, s.RPC)
	if s.Sync == nil {
		return errors.New("api: Services.Sync is nil")
	}
	registerSync(r, s.Sync)
	if s.Thread == nil {
		return errors.New("api: Services.Thread is nil")
	}
	registerThread(r, s.Thread)
	if s.View == nil {
		return errors.New("api: Services.View is nil")
	}
	registerView(r, s.View)
	return nil
}

// Methods is every method's wire name, in schema order.
var Methods = []string{
	"account.list",
	"account.get",
	"account.create",
	"account.update",
	"account.delete",
	"account.setPassword",
	"account.discover",
	"account.authorize",
	"account.verify",
	"address.suggest",
	"draft.create",
	"draft.open",
	"draft.get",
	"draft.list",
	"draft.update",
	"draft.attach",
	"draft.detach",
	"draft.delete",
	"draft.send",
	"events.subscribe",
	"identity.list",
	"identity.update",
	"mailbox.list",
	"message.get",
	"message.body",
	"message.summaries",
	"message.render",
	"message.part",
	"message.setFlags",
	"message.move",
	"message.delete",
	"oauth.setClient",
	"oauth.getClient",
	"outbox.list",
	"outbox.cancel",
	"outbox.retry",
	"rpc.hello",
	"sync.status",
	"sync.now",
	"thread.messages",
	"view.open",
	"view.range",
	"view.close",
}

// DecodeEvent decodes the data of the named event.
func DecodeEvent(name string, data jsontext.Value) (Event, error) {
	switch name {
	case "account.changed":
		var e AccountChanged
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	case "draft.changed":
		var e DraftChanged
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	case "mailbox.changed":
		var e MailboxChanged
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	case "message.changed":
		var e MessageChanged
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	case "message.removed":
		var e MessageRemoved
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	case "outbox.changed":
		var e OutboxChanged
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	case "sync.progress":
		var e SyncProgress
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	case "view.delta":
		var e ViewDelta
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	}
	return nil, fmt.Errorf("unknown event %q", name)
}
