// Code generated by rpcgen from schema/rpc. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"time"
)

// Keep imports used when a schema has no time or json fields.
var (
	_ time.Time
	_ jsontext.Value
)

// Protocol is the protocol major version this package speaks.
const Protocol = 1

// Error codes. JSON-RPC 2.0 defines the negative codes.
const (
	// The request is not valid JSON.
	CodeParseError ErrorCode = -32700
	// The request is not a valid JSON-RPC 2.0 request object.
	CodeInvalidRequest ErrorCode = -32600
	// The method does not exist.
	CodeMethodNotFound ErrorCode = -32601
	// The params are missing, unknown or invalid.
	CodeInvalidParams ErrorCode = -32602
	// The server failed; the message says why.
	CodeInternal ErrorCode = -32603
	// The referenced entity does not exist.
	CodeNotFound ErrorCode = 1001
	// The request conflicts with existing state, such as a duplicate account.
	CodeConflict ErrorCode = 1002
	// The server does not speak the client's protocol major version.
	CodeProtocolMismatch ErrorCode = 1003
	// The connection has not completed rpc.hello.
	CodeNotReady ErrorCode = 1004
	// The operation cannot run now, for example while offline; retrying later can
	// succeed.
	CodeUnavailable ErrorCode = 1005
	// The account's credentials were rejected or have expired; the user must sign
	// in again.
	CodeAuthRequired ErrorCode = 1006
)

// Sentinels for errors.Is: an *Error matches the sentinel with its code.
var (
	ErrParseError       = &Error{Code: CodeParseError}
	ErrInvalidRequest   = &Error{Code: CodeInvalidRequest}
	ErrMethodNotFound   = &Error{Code: CodeMethodNotFound}
	ErrInvalidParams    = &Error{Code: CodeInvalidParams}
	ErrInternal         = &Error{Code: CodeInternal}
	ErrNotFound         = &Error{Code: CodeNotFound}
	ErrConflict         = &Error{Code: CodeConflict}
	ErrProtocolMismatch = &Error{Code: CodeProtocolMismatch}
	ErrNotReady         = &Error{Code: CodeNotReady}
	ErrUnavailable      = &Error{Code: CodeUnavailable}
	ErrAuthRequired     = &Error{Code: CodeAuthRequired}
)

// String is the code's schema name.
func (c ErrorCode) String() string {
	switch c {
	case CodeParseError:
		return "parseError"
	case CodeInvalidRequest:
		return "invalidRequest"
	case CodeMethodNotFound:
		return "methodNotFound"
	case CodeInvalidParams:
		return "invalidParams"
	case CodeInternal:
		return "internal"
	case CodeNotFound:
		return "notFound"
	case CodeConflict:
		return "conflict"
	case CodeProtocolMismatch:
		return "protocolMismatch"
	case CodeNotReady:
		return "notReady"
	case CodeUnavailable:
		return "unavailable"
	case CodeAuthRequired:
		return "authRequired"
	}
	return fmt.Sprintf("ErrorCode(%d)", int(c))
}

// ParseError returns an error with CodeParseError.
func ParseError(format string, args ...any) *Error { return Errorf(CodeParseError, format, args...) }

// InvalidRequest returns an error with CodeInvalidRequest.
func InvalidRequest(format string, args ...any) *Error {
	return Errorf(CodeInvalidRequest, format, args...)
}

// MethodNotFound returns an error with CodeMethodNotFound.
func MethodNotFound(format string, args ...any) *Error {
	return Errorf(CodeMethodNotFound, format, args...)
}

// InvalidParams returns an error with CodeInvalidParams.
func InvalidParams(format string, args ...any) *Error {
	return Errorf(CodeInvalidParams, format, args...)
}

// Internal returns an error with CodeInternal.
func Internal(format string, args ...any) *Error { return Errorf(CodeInternal, format, args...) }

// NotFound returns an error with CodeNotFound.
func NotFound(format string, args ...any) *Error { return Errorf(CodeNotFound, format, args...) }

// Conflict returns an error with CodeConflict.
func Conflict(format string, args ...any) *Error { return Errorf(CodeConflict, format, args...) }

// ProtocolMismatch returns an error with CodeProtocolMismatch.
func ProtocolMismatch(format string, args ...any) *Error {
	return Errorf(CodeProtocolMismatch, format, args...)
}

// NotReady returns an error with CodeNotReady.
func NotReady(format string, args ...any) *Error { return Errorf(CodeNotReady, format, args...) }

// Unavailable returns an error with CodeUnavailable.
func Unavailable(format string, args ...any) *Error { return Errorf(CodeUnavailable, format, args...) }

// AuthRequired returns an error with CodeAuthRequired.
func AuthRequired(format string, args ...any) *Error {
	return Errorf(CodeAuthRequired, format, args...)
}

// ---- account ----

// AccountKind: The provider family, which selects the sync strategy and
// server quirks.
type AccountKind string

const (
	// Generic IMAP and SMTP.
	AccountKindIMAP AccountKind = "imap"
	// Google Gmail and Workspace (labels, X-GM extensions).
	AccountKindGmail AccountKind = "gmail"
	// Microsoft 365 and Outlook.com.
	AccountKindMicrosoft AccountKind = "microsoft"
	// Apple iCloud Mail.
	AccountKindICloud AccountKind = "icloud"
)

// Valid reports whether v is one of the declared values.
func (v AccountKind) Valid() bool {
	switch v {
	case AccountKindIMAP, AccountKindGmail, AccountKindMicrosoft, AccountKindICloud:
		return true
	}
	return false
}

// AuthKind: How the account authenticates to its servers.
type AuthKind string

const (
	// A password or app-specific password, kept in the secret store.
	AuthKindPassword AuthKind = "password"
	// OAuth 2.0 tokens (SASL XOAUTH2), kept in the secret store.
	AuthKindOAuth2 AuthKind = "oauth2"
)

// Valid reports whether v is one of the declared values.
func (v AuthKind) Valid() bool {
	switch v {
	case AuthKindPassword, AuthKindOAuth2:
		return true
	}
	return false
}

// TLSMode: How a connection is secured.
type TLSMode string

const (
	// TLS from the first byte (IMAPS 993, SMTPS 465).
	TLSModeTLS TLSMode = "tls"
	// Plain connection upgraded with STARTTLS (143, 587).
	TLSModeStartTLS TLSMode = "starttls"
	// No TLS. Only for local test servers.
	TLSModeInsecure TLSMode = "insecure"
)

// Valid reports whether v is one of the declared values.
func (v TLSMode) Valid() bool {
	switch v {
	case TLSModeTLS, TLSModeStartTLS, TLSModeInsecure:
		return true
	}
	return false
}

// ServerConfig: Where and how to reach one server.
type ServerConfig struct {
	Host string  `json:"host"`
	Port int64   `json:"port"`
	TLS  TLSMode `json:"tls"`
	// Login name; often the email address.
	Username string `json:"username"`
}

// Account: A configured mail account.
type Account struct {
	// Stable local identifier.
	ID   int64       `json:"id"`
	Kind AccountKind `json:"kind"`
	// The account's primary address.
	Email string `json:"email"`
	// The sender name used in From headers.
	DisplayName string       `json:"displayName"`
	Auth        AuthKind     `json:"auth"`
	IMAP        ServerConfig `json:"imap"`
	SMTP        ServerConfig `json:"smtp"`
	CreatedAt   time.Time    `json:"createdAt"`
}

// AccountListParams holds the params of account.list.
type AccountListParams struct{}

// AccountGetParams holds the params of account.get.
type AccountGetParams struct {
	ID int64 `json:"id"`
}

// AccountCreateParams holds the params of account.create.
type AccountCreateParams struct {
	Kind        AccountKind  `json:"kind"`
	Email       string       `json:"email"`
	DisplayName string       `json:"displayName"`
	Auth        AuthKind     `json:"auth"`
	IMAP        ServerConfig `json:"imap"`
	SMTP        ServerConfig `json:"smtp"`
}

// AccountUpdateParams holds the params of account.update.
type AccountUpdateParams struct {
	ID          int64         `json:"id"`
	DisplayName *string       `json:"displayName,omitzero"`
	IMAP        *ServerConfig `json:"imap,omitzero"`
	SMTP        *ServerConfig `json:"smtp,omitzero"`
}

// AccountDeleteParams holds the params of account.delete.
type AccountDeleteParams struct {
	ID int64 `json:"id"`
}

// AccountService: Mail accounts and their server settings. Credentials never
// cross the RPC boundary.
type AccountService interface {
	// List implements account.list. All accounts, oldest first.
	List(ctx context.Context, p *AccountListParams) ([]Account, error)
	// Get implements account.get. One account.
	Get(ctx context.Context, p *AccountGetParams) (*Account, error)
	// Create implements account.create. Add an account. The email address must be
	// unique.
	Create(ctx context.Context, p *AccountCreateParams) (*Account, error)
	// Update implements account.update. Change an account's settings. Omitted
	// fields keep their values.
	Update(ctx context.Context, p *AccountUpdateParams) (*Account, error)
	// Delete implements account.delete. Remove an account and everything stored
	// for it.
	Delete(ctx context.Context, p *AccountDeleteParams) error
}

func registerAccount(r *Router, s AccountService) {
	r.handle("account.list", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountListParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.List(ctx, &p)
	})
	r.handle("account.get", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountGetParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Get(ctx, &p)
	})
	r.handle("account.create", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountCreateParams
		if err := decodeParams(raw, &p, []string{"kind", "email", "displayName", "auth", "imap", "smtp"}); err != nil {
			return nil, err
		}
		return s.Create(ctx, &p)
	})
	r.handle("account.update", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountUpdateParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return s.Update(ctx, &p)
	})
	r.handle("account.delete", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p AccountDeleteParams
		if err := decodeParams(raw, &p, []string{"id"}); err != nil {
			return nil, err
		}
		return nil, s.Delete(ctx, &p)
	})
}

// AccountClient calls the account methods; it implements AccountService.
type AccountClient struct{ c *Client }

// Account returns the account methods.
func (c *Client) Account() AccountClient { return AccountClient{c} }

var _ AccountService = AccountClient{}

// List calls account.list.
func (x AccountClient) List(ctx context.Context, p *AccountListParams) ([]Account, error) {
	var r []Account
	err := x.c.Call(ctx, "account.list", p, &r)
	return r, err
}

// Get calls account.get.
func (x AccountClient) Get(ctx context.Context, p *AccountGetParams) (*Account, error) {
	var r Account
	err := x.c.Call(ctx, "account.get", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Create calls account.create.
func (x AccountClient) Create(ctx context.Context, p *AccountCreateParams) (*Account, error) {
	var r Account
	err := x.c.Call(ctx, "account.create", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Update calls account.update.
func (x AccountClient) Update(ctx context.Context, p *AccountUpdateParams) (*Account, error) {
	var r Account
	err := x.c.Call(ctx, "account.update", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Delete calls account.delete.
func (x AccountClient) Delete(ctx context.Context, p *AccountDeleteParams) error {
	return x.c.Call(ctx, "account.delete", p, nil)
}

// AccountChanged: An account was created, updated or deleted.
type AccountChanged struct {
	ID      int64 `json:"id"`
	Deleted bool  `json:"deleted"`
}

// EventName is the wire name of AccountChanged.
func (AccountChanged) EventName() string { return "account.changed" }

// Durable reports whether AccountChanged is kept in the changes log.
func (AccountChanged) Durable() bool { return true }

// ---- events ----

// Subscription: The state of a new subscription.
type Subscription struct {
	// The latest durable sequence number when the subscription started.
	Seq int64 `json:"seq"`
	// True when sinceSeq is older than the retained log; the client must refetch
	// all state.
	Resync bool `json:"resync"`
}

// EventsSubscribeParams holds the params of events.subscribe.
type EventsSubscribeParams struct {
	// Replay durable events after this sequence number. Omit to receive live
	// events only.
	SinceSeq *int64 `json:"sinceSeq,omitzero"`
}

// EventsService: Change notifications. After events.subscribe, the server
// sends JSON-RPC notifications with method "event" on the same connection.
// Durable events carry a sequence number and are kept in the changes log, so
// a client that reconnects can resume from the last sequence number it saw.
type EventsService interface {
	// Subscribe implements events.subscribe. Start receiving events on this
	// connection. Durable events after sinceSeq are replayed before live events.
	Subscribe(ctx context.Context, p *EventsSubscribeParams) (*Subscription, error)
}

func registerEvents(r *Router, s EventsService) {
	r.handle("events.subscribe", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p EventsSubscribeParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.Subscribe(ctx, &p)
	})
}

// EventsClient calls the events methods; it implements EventsService.
type EventsClient struct{ c *Client }

// Events returns the events methods.
func (c *Client) Events() EventsClient { return EventsClient{c} }

var _ EventsService = EventsClient{}

// Subscribe calls events.subscribe.
func (x EventsClient) Subscribe(ctx context.Context, p *EventsSubscribeParams) (*Subscription, error) {
	var r Subscription
	err := x.c.Call(ctx, "events.subscribe", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// ---- mailbox ----

// MailboxRole: What a mailbox is for, from SPECIAL-USE attributes or name
// heuristics.
type MailboxRole string

const (
	// An ordinary user folder.
	MailboxRoleNone    MailboxRole = "none"
	MailboxRoleInbox   MailboxRole = "inbox"
	MailboxRoleDrafts  MailboxRole = "drafts"
	MailboxRoleSent    MailboxRole = "sent"
	MailboxRoleArchive MailboxRole = "archive"
	MailboxRoleJunk    MailboxRole = "junk"
	MailboxRoleTrash   MailboxRole = "trash"
	// All messages (Gmail All Mail).
	MailboxRoleAll MailboxRole = "all"
	// A server-side flagged view (Gmail Starred).
	MailboxRoleFlagged MailboxRole = "flagged"
)

// Valid reports whether v is one of the declared values.
func (v MailboxRole) Valid() bool {
	switch v {
	case MailboxRoleNone, MailboxRoleInbox, MailboxRoleDrafts, MailboxRoleSent, MailboxRoleArchive, MailboxRoleJunk, MailboxRoleTrash, MailboxRoleAll, MailboxRoleFlagged:
		return true
	}
	return false
}

// Mailbox: One mailbox of one account.
type Mailbox struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountId"`
	// Full server path, decoded from modified UTF-7.
	Path string `json:"path"`
	// The last path component, for display.
	Name string `json:"name"`
	// The server's hierarchy delimiter; empty when flat.
	Delimiter string      `json:"delimiter"`
	Role      MailboxRole `json:"role"`
	// Messages stored locally for this mailbox.
	Total int64 `json:"total"`
	// Unread messages stored locally for this mailbox.
	Unread int64 `json:"unread"`
}

// MailboxListParams holds the params of mailbox.list.
type MailboxListParams struct {
	// Limit to one account. Omit for all accounts.
	AccountID *int64 `json:"accountId,omitzero"`
}

// MailboxService: Mailboxes (IMAP folders, and Gmail labels shown as
// folders).
type MailboxService interface {
	// List implements mailbox.list. Mailboxes ordered by account, role, then
	// path.
	List(ctx context.Context, p *MailboxListParams) ([]Mailbox, error)
}

func registerMailbox(r *Router, s MailboxService) {
	r.handle("mailbox.list", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p MailboxListParams
		if err := decodeParams(raw, &p, nil); err != nil {
			return nil, err
		}
		return s.List(ctx, &p)
	})
}

// MailboxClient calls the mailbox methods; it implements MailboxService.
type MailboxClient struct{ c *Client }

// Mailbox returns the mailbox methods.
func (c *Client) Mailbox() MailboxClient { return MailboxClient{c} }

var _ MailboxService = MailboxClient{}

// List calls mailbox.list.
func (x MailboxClient) List(ctx context.Context, p *MailboxListParams) ([]Mailbox, error) {
	var r []Mailbox
	err := x.c.Call(ctx, "mailbox.list", p, &r)
	return r, err
}

// MailboxChanged: A mailbox was created, renamed, deleted, or its counts
// changed.
type MailboxChanged struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountId"`
	Deleted   bool  `json:"deleted"`
}

// EventName is the wire name of MailboxChanged.
func (MailboxChanged) EventName() string { return "mailbox.changed" }

// Durable reports whether MailboxChanged is kept in the changes log.
func (MailboxChanged) Durable() bool { return true }

// ---- rpc ----

// Hello: Server identity and the negotiated protocol.
type Hello struct {
	// Protocol major version the server speaks.
	Protocol int64 `json:"protocol"`
	// Server name and version, for logs.
	Server string `json:"server"`
}

// RPCHelloParams holds the params of rpc.hello.
type RPCHelloParams struct {
	// Protocol major version the client speaks.
	Protocol int64 `json:"protocol"`
	// Client name and version, for logs.
	Client string `json:"client"`
}

// RPCService: Connection setup. A client calls rpc.hello first on every
// connection; the server answers any other method with notReady until hello
// succeeds.
type RPCService interface {
	// Hello implements rpc.hello. Negotiate the protocol major version. Changes
	// within a major version are additive only.
	Hello(ctx context.Context, p *RPCHelloParams) (*Hello, error)
}

func registerRPC(r *Router, s RPCService) {
	r.handle("rpc.hello", func(ctx context.Context, raw jsontext.Value) (any, error) {
		var p RPCHelloParams
		if err := decodeParams(raw, &p, []string{"protocol", "client"}); err != nil {
			return nil, err
		}
		return s.Hello(ctx, &p)
	})
}

// RPCClient calls the rpc methods; it implements RPCService.
type RPCClient struct{ c *Client }

// RPC returns the rpc methods.
func (c *Client) RPC() RPCClient { return RPCClient{c} }

var _ RPCService = RPCClient{}

// Hello calls rpc.hello.
func (x RPCClient) Hello(ctx context.Context, p *RPCHelloParams) (*Hello, error) {
	var r Hello
	err := x.c.Call(ctx, "rpc.hello", p, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Services is one implementation per domain, for NewRouter.
type Services struct {
	Account AccountService
	Events  EventsService
	Mailbox MailboxService
	RPC     RPCService
}

func (s Services) register(r *Router) error {
	if s.Account == nil {
		return errors.New("api: Services.Account is nil")
	}
	registerAccount(r, s.Account)
	if s.Events == nil {
		return errors.New("api: Services.Events is nil")
	}
	registerEvents(r, s.Events)
	if s.Mailbox == nil {
		return errors.New("api: Services.Mailbox is nil")
	}
	registerMailbox(r, s.Mailbox)
	if s.RPC == nil {
		return errors.New("api: Services.RPC is nil")
	}
	registerRPC(r, s.RPC)
	return nil
}

// Methods is every method's wire name, in schema order.
var Methods = []string{
	"account.list",
	"account.get",
	"account.create",
	"account.update",
	"account.delete",
	"events.subscribe",
	"mailbox.list",
	"rpc.hello",
}

// DecodeEvent decodes the data of the named event.
func DecodeEvent(name string, data jsontext.Value) (Event, error) {
	switch name {
	case "account.changed":
		var e AccountChanged
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	case "mailbox.changed":
		var e MailboxChanged
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, fmt.Errorf("decode event %s: %w", name, err)
		}
		return e, nil
	}
	return nil, fmt.Errorf("unknown event %q", name)
}
