// Command zonesgen generates internal/calendar/zones_gen.go, the Windows
// time zone names Outlook writes in TZID mapped to IANA zones, from CLDR's
// windowsZones.xml at a pinned release whose SHA-256 it checks
// (ADR-0018; frostyard/core ADR-0023). Run it with make zones when CLDR
// is bumped; the generated file is committed.
//
//	zonesgen [-in windowsZones.xml] [-out internal/calendar/zones_gen.go]
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/xml"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"maps"
	"net/http"
	"os"
	"slices"
	"strings"
	"time"
)

// The pinned CLDR release and its windowsZones.xml's SHA-256.
const (
	release = "release-48"
	source  = "https://raw.githubusercontent.com/unicode-org/cldr/" + release + "/common/supplemental/windowsZones.xml"
	sum     = "9cf3db6a31fb382fee21b70be6feba1e82766b0fcd06e6261fb7936a73e537ff"
)

func main() {
	if err := run(context.Background(), os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "zonesgen:", err)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("zonesgen", flag.ContinueOnError)
	in := fs.String("in", "", "read windowsZones.xml from this file instead of downloading it")
	out := fs.String("out", "internal/calendar/zones_gen.go", "the Go file to write")
	if err := fs.Parse(args); err != nil {
		return err
	}
	data, err := load(ctx, *in)
	if err != nil {
		return err
	}
	if got := sha256.Sum256(data); hex.EncodeToString(got[:]) != sum {
		return fmt.Errorf("windowsZones.xml has SHA-256 %x, want %s (%s)", got, sum, release)
	}
	zones, err := parse(data)
	if err != nil {
		return err
	}
	src, err := generate(zones)
	if err != nil {
		return err
	}
	return os.WriteFile(*out, src, 0o644)
}

func load(ctx context.Context, path string) ([]byte, error) {
	if path != "" {
		return os.ReadFile(path)
	}
	ctx, cancel := context.WithTimeout(ctx, time.Minute)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, source, nil)
	if err != nil {
		return nil, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: HTTP %d", source, resp.StatusCode)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 1<<20))
}

// parse maps each Windows zone to its "001" (golden) IANA zone: the first
// of the type's space-separated list.
func parse(data []byte) (map[string]string, error) {
	var doc struct {
		Zones []struct {
			Other     string `xml:"other,attr"`
			Territory string `xml:"territory,attr"`
			Type      string `xml:"type,attr"`
		} `xml:"windowsZones>mapTimezones>mapZone"`
	}
	if err := xml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("windowsZones.xml: %w", err)
	}
	out := map[string]string{}
	for _, z := range doc.Zones {
		if z.Territory != "001" {
			continue
		}
		iana, _, _ := strings.Cut(z.Type, " ")
		if iana == "" {
			return nil, fmt.Errorf("windowsZones.xml: %q has no IANA zone", z.Other)
		}
		out[z.Other] = iana
	}
	if len(out) < 100 {
		return nil, errors.New("windowsZones.xml: fewer than 100 zones; the format changed")
	}
	return out, nil
}

func generate(zones map[string]string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/zonesgen from CLDR %s windowsZones.xml; DO NOT EDIT.\n\n", release)
	b.WriteString("package calendar\n\n")
	b.WriteString("// windowsZones maps the Windows time zone names Outlook writes in TZID to\n")
	b.WriteString("// IANA zones (CLDR's territory 001 mapping).\n")
	b.WriteString("var windowsZones = map[string]string{\n")
	for _, k := range slices.Sorted(maps.Keys(zones)) {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, zones[k])
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
